<?php $icons_set = array();

/* FONTAWSOME ICONS SET*/
$icons_set['fa']['fa-glass'] = array("class"=>'fa',"tags"=>'glass',"unicode"=>'f000');
$icons_set['fa']['fa-music'] = array("class"=>'fa',"tags"=>'music',"unicode"=>'f001');
$icons_set['fa']['fa-search'] = array("class"=>'fa',"tags"=>'search',"unicode"=>'f002');
$icons_set['fa']['fa-envelope-o'] = array("class"=>'fa',"tags"=>'envelope-o',"unicode"=>'f003');
$icons_set['fa']['fa-heart'] = array("class"=>'fa',"tags"=>'heart',"unicode"=>'f004');
$icons_set['fa']['fa-star'] = array("class"=>'fa',"tags"=>'star',"unicode"=>'f005');
$icons_set['fa']['fa-star-o'] = array("class"=>'fa',"tags"=>'star-o',"unicode"=>'f006');
$icons_set['fa']['fa-user'] = array("class"=>'fa',"tags"=>'user',"unicode"=>'f007');
$icons_set['fa']['fa-film'] = array("class"=>'fa',"tags"=>'film',"unicode"=>'f008');
$icons_set['fa']['fa-th-large'] = array("class"=>'fa',"tags"=>'th-large',"unicode"=>'f009');
$icons_set['fa']['fa-th'] = array("class"=>'fa',"tags"=>'th',"unicode"=>'f00a');
$icons_set['fa']['fa-th-list'] = array("class"=>'fa',"tags"=>'th-list',"unicode"=>'f00b');
$icons_set['fa']['fa-check'] = array("class"=>'fa',"tags"=>'check',"unicode"=>'f00c');
$icons_set['fa']['fa-times'] = array("class"=>'fa',"tags"=>'times',"unicode"=>'f00d');
$icons_set['fa']['fa-search-plus'] = array("class"=>'fa',"tags"=>'search-plus',"unicode"=>'f00e');
$icons_set['fa']['fa-search-minus'] = array("class"=>'fa',"tags"=>'search-minus',"unicode"=>'f010');
$icons_set['fa']['fa-power-off'] = array("class"=>'fa',"tags"=>'power-off',"unicode"=>'f011');
$icons_set['fa']['fa-signal'] = array("class"=>'fa',"tags"=>'signal',"unicode"=>'f012');
$icons_set['fa']['fa-gear'] = array("class"=>'fa',"tags"=>'gear',"unicode"=>'f013');
$icons_set['fa']['fa-cog'] = array("class"=>'fa',"tags"=>'cog',"unicode"=>'f013');
$icons_set['fa']['fa-trash-o'] = array("class"=>'fa',"tags"=>'trash-o',"unicode"=>'f014');
$icons_set['fa']['fa-home'] = array("class"=>'fa',"tags"=>'home',"unicode"=>'f015');
$icons_set['fa']['fa-file-o'] = array("class"=>'fa',"tags"=>'file-o',"unicode"=>'f016');
$icons_set['fa']['fa-clock-o'] = array("class"=>'fa',"tags"=>'clock-o',"unicode"=>'f017');
$icons_set['fa']['fa-road'] = array("class"=>'fa',"tags"=>'road',"unicode"=>'f018');
$icons_set['fa']['fa-download'] = array("class"=>'fa',"tags"=>'download',"unicode"=>'f019');
$icons_set['fa']['fa-arrow-circle-o-down'] = array("class"=>'fa',"tags"=>'arrow-circle-o-down',"unicode"=>'f01a');
$icons_set['fa']['fa-arrow-circle-o-up'] = array("class"=>'fa',"tags"=>'arrow-circle-o-up',"unicode"=>'f01b');
$icons_set['fa']['fa-inbox'] = array("class"=>'fa',"tags"=>'inbox',"unicode"=>'f01c');
$icons_set['fa']['fa-play-circle-o'] = array("class"=>'fa',"tags"=>'play-circle-o',"unicode"=>'f01d');
$icons_set['fa']['fa-rotate-right'] = array("class"=>'fa',"tags"=>'fa-rotate-right',"unicode"=>'f01e');
$icons_set['fa']['fa-repeat'] = array("class"=>'fa',"tags"=>'fa-repeat',"unicode"=>'f01e');
$icons_set['fa']['fa-refresh'] = array("class"=>'fa',"tags"=>'fa-refresh',"unicode"=>'f021');
$icons_set['fa']['fa-list-alt'] = array("class"=>'fa',"tags"=>'fa-list-alt',"unicode"=>'f022');
$icons_set['fa']['fa-lock'] = array("class"=>'fa',"tags"=>'lock',"unicode"=>'f023');
$icons_set['fa']['fa-flag'] = array("class"=>'fa',"tags"=>'flag',"unicode"=>'f024');
$icons_set['fa']['fa-headphones'] = array("class"=>'fa',"tags"=>'headphones',"unicode"=>'f025');
$icons_set['fa']['fa-volume-off'] = array("class"=>'fa',"tags"=>'volume-off',"unicode"=>'f026');
$icons_set['fa']['fa-volume-down'] = array("class"=>'fa',"tags"=>'volume-down',"unicode"=>'f027');
$icons_set['fa']['fa-volume-up'] = array("class"=>'fa',"tags"=>'volume-up',"unicode"=>'f028');
$icons_set['fa']['fa-qrcode'] = array("class"=>'fa',"tags"=>'qrcode',"unicode"=>'f029');
$icons_set['fa']['fa-barcode'] = array("class"=>'fa',"tags"=>'barcode',"unicode"=>'f02a');
$icons_set['fa']['fa-tag'] = array("class"=>'fa',"tags"=>'tag',"unicode"=>'f02b');
$icons_set['fa']['fa-tags'] = array("class"=>'fa',"tags"=>'tags',"unicode"=>'f02c');
$icons_set['fa']['fa-book'] = array("class"=>'fa',"tags"=>'book',"unicode"=>'f02d');
$icons_set['fa']['fa-bookmark'] = array("class"=>'fa',"tags"=>'bookmark',"unicode"=>'f02e');
$icons_set['fa']['fa-print'] = array("class"=>'fa',"tags"=>'print',"unicode"=>'f02f');
$icons_set['fa']['fa-camera'] = array("class"=>'fa',"tags"=>'camera',"unicode"=>'f030');
$icons_set['fa']['fa-font'] = array("class"=>'fa',"tags"=>'font',"unicode"=>'f031');
$icons_set['fa']['fa-bold'] = array("class"=>'fa',"tags"=>'bold',"unicode"=>'f032');
$icons_set['fa']['fa-italic'] = array("class"=>'fa',"tags"=>'italic',"unicode"=>'f033');
$icons_set['fa']['fa-text-height'] = array("class"=>'fa',"tags"=>'text-height',"unicode"=>'f034');
$icons_set['fa']['fa-text-width'] = array("class"=>'fa',"tags"=>'text-width',"unicode"=>'f035');
$icons_set['fa']['fa-align-left'] = array("class"=>'fa',"tags"=>'align-left',"unicode"=>'f036');
$icons_set['fa']['fa-align-center'] = array("class"=>'fa',"tags"=>'align-center',"unicode"=>'f037');
$icons_set['fa']['fa-align-right'] = array("class"=>'fa',"tags"=>'align-right',"unicode"=>'f038');
$icons_set['fa']['fa-align-justify'] = array("class"=>'fa',"tags"=>'align-justify',"unicode"=>'f039');
$icons_set['fa']['fa-list'] = array("class"=>'fa',"tags"=>'list',"unicode"=>'f03a');
$icons_set['fa']['fa-dedent'] = array("class"=>'fa',"tags"=>'dedent',"unicode"=>'f03b');
$icons_set['fa']['fa-outdent'] = array("class"=>'fa',"tags"=>'outdent',"unicode"=>'f03b');
$icons_set['fa']['fa-indent'] = array("class"=>'fa',"tags"=>'indent',"unicode"=>'f03c');
$icons_set['fa']['fa-video-camera'] = array("class"=>'fa',"tags"=>'video-camera',"unicode"=>'f03d');
$icons_set['fa']['fa-picture-o'] = array("class"=>'fa',"tags"=>'picture-o',"unicode"=>'f03e');
$icons_set['fa']['fa-pencil'] = array("class"=>'fa',"tags"=>'pencil',"unicode"=>'f040');
$icons_set['fa']['fa-map-marker'] = array("class"=>'fa',"tags"=>'map-marker',"unicode"=>'f041');
$icons_set['fa']['fa-adjust'] = array("class"=>'fa',"tags"=>'adjust',"unicode"=>'f042');
$icons_set['fa']['fa-tint'] = array("class"=>'fa',"tags"=>'tint',"unicode"=>'f043');
$icons_set['fa']['fa-edit'] = array("class"=>'fa',"tags"=>'edit',"unicode"=>'f044');
$icons_set['fa']['fa-pencil-square-o'] = array("class"=>'fa',"tags"=>'pencil-square-o',"unicode"=>'f044');
$icons_set['fa']['fa-share-square-o'] = array("class"=>'fa',"tags"=>'share-square-o',"unicode"=>'f045');
$icons_set['fa']['fa-check-square-o'] = array("class"=>'fa',"tags"=>'check-square-o',"unicode"=>'f046');
$icons_set['fa']['fa-arrows'] = array("class"=>'fa',"tags"=>'arrows',"unicode"=>'f047');
$icons_set['fa']['fa-step-backward'] = array("class"=>'fa',"tags"=>'step-backward',"unicode"=>'f048');
$icons_set['fa']['fa-fast-backward'] = array("class"=>'fa',"tags"=>'fast-backward',"unicode"=>'f049');
$icons_set['fa']['fa-backward'] = array("class"=>'fa',"tags"=>'fast-backward',"unicode"=>'f04a');
$icons_set['fa']['fa-play'] = array("class"=>'fa',"tags"=>'play',"unicode"=>'f04b');
$icons_set['fa']['fa-pause'] = array("class"=>'fa',"tags"=>'pause',"unicode"=>'f04c');
$icons_set['fa']['fa-stop'] = array("class"=>'fa',"tags"=>'stop',"unicode"=>'f04d');
$icons_set['fa']['fa-forward'] = array("class"=>'fa',"tags"=>'forward',"unicode"=>'f04e');
$icons_set['fa']['fa-fast-forward'] = array("class"=>'fa',"tags"=>'fast-forward',"unicode"=>'f050');
$icons_set['fa']['fa-step-forward'] = array("class"=>'fa',"tags"=>'step-forward',"unicode"=>'f051');
$icons_set['fa']['fa-eject'] = array("class"=>'fa',"tags"=>'eject',"unicode"=>'f052');
$icons_set['fa']['fa-chevron-left'] = array("class"=>'fa',"tags"=>'chevron-left',"unicode"=>'f053');
$icons_set['fa']['fa-chevron-right'] = array("class"=>'fa',"tags"=>'chevron-right',"unicode"=>'f054');
$icons_set['fa']['fa-plus-circle'] = array("class"=>'fa',"tags"=>'plus-circle',"unicode"=>'f055');
$icons_set['fa']['fa-minus-circle'] = array("class"=>'fa',"tags"=>'minus-circle',"unicode"=>'f056');
$icons_set['fa']['fa-times-circle'] = array("class"=>'fa',"tags"=>'times-circle',"unicode"=>'f057');
$icons_set['fa']['fa-check-circle'] = array("class"=>'fa',"tags"=>'check-circle',"unicode"=>'f058');
$icons_set['fa']['fa-question-circle'] = array("class"=>'fa',"tags"=>'question-circle',"unicode"=>'f059');
$icons_set['fa']['fa-info-circle'] = array("class"=>'fa',"tags"=>'info-circle',"unicode"=>'f05a');
$icons_set['fa']['fa-crosshairs'] = array("class"=>'fa',"tags"=>'crosshairs',"unicode"=>'f05b');
$icons_set['fa']['fa-times-circle-o'] = array("class"=>'fa',"tags"=>'times-circle-o',"unicode"=>'f05c');
$icons_set['fa']['fa-check-circle-o'] = array("class"=>'fa',"tags"=>'check-circle-o',"unicode"=>'f05d');
$icons_set['fa']['fa-ban'] = array("class"=>'fa',"tags"=>'ban',"unicode"=>'f05e');
$icons_set['fa']['fa-arrow-left'] = array("class"=>'fa',"tags"=>'arrow-left',"unicode"=>'f060');
$icons_set['fa']['fa-arrow-right'] = array("class"=>'fa',"tags"=>'arrow-right',"unicode"=>'f061');
$icons_set['fa']['fa-arrow-up'] = array("class"=>'fa',"tags"=>'arrow-up',"unicode"=>'f062');
$icons_set['fa']['fa-arrow-down'] = array("class"=>'fa',"tags"=>'arrow-down',"unicode"=>'f063');
$icons_set['fa']['fa-mail-forward'] = array("class"=>'fa',"tags"=>'mail-forward',"unicode"=>'f064');
$icons_set['fa']['fa-share'] = array("class"=>'fa',"tags"=>'share',"unicode"=>'f064');
$icons_set['fa']['fa-expand'] = array("class"=>'fa',"tags"=>'expand',"unicode"=>'f065');
$icons_set['fa']['fa-compress'] = array("class"=>'fa',"tags"=>'compress',"unicode"=>'f066');
$icons_set['fa']['fa-plus'] = array("class"=>'fa',"tags"=>'plus',"unicode"=>'f067');
$icons_set['fa']['fa-minus'] = array("class"=>'fa',"tags"=>'minus',"unicode"=>'f068');
$icons_set['fa']['fa-asterisk'] = array("class"=>'fa',"tags"=>'asterisk',"unicode"=>'f069');
$icons_set['fa']['fa-exclamation-circle'] = array("class"=>'fa',"tags"=>'exclamation-circle',"unicode"=>'f06a');
$icons_set['fa']['fa-gift'] = array("class"=>'fa',"tags"=>'gift',"unicode"=>'f06b');
$icons_set['fa']['fa-leaf'] = array("class"=>'fa',"tags"=>'leaf',"unicode"=>'f06c');
$icons_set['fa']['fa-fire'] = array("class"=>'fa',"tags"=>'fire',"unicode"=>'f06d');
$icons_set['fa']['fa-eye'] = array("class"=>'fa',"tags"=>'eye',"unicode"=>'f06e');
$icons_set['fa']['fa-eye-slash'] = array("class"=>'fa',"tags"=>'eye-slash',"unicode"=>'f070');
$icons_set['fa']['fa-warning'] = array("class"=>'fa',"tags"=>'warning',"unicode"=>'f071');
$icons_set['fa']['fa-exclamation-triangle'] = array("class"=>'fa',"tags"=>'exclamation-triangle',"unicode"=>'f071');
$icons_set['fa']['fa-plane'] = array("class"=>'fa',"tags"=>'plane',"unicode"=>'f072');
$icons_set['fa']['fa-calendar'] = array("class"=>'fa',"tags"=>'calendar',"unicode"=>'f073');
$icons_set['fa']['fa-random'] = array("class"=>'fa',"tags"=>'random',"unicode"=>'f074');
$icons_set['fa']['fa-comment'] = array("class"=>'fa',"tags"=>'comment',"unicode"=>'f075');
$icons_set['fa']['fa-magnet'] = array("class"=>'fa',"tags"=>'magnet',"unicode"=>'f076');
$icons_set['fa']['fa-chevron-up'] = array("class"=>'fa',"tags"=>'chevron-up',"unicode"=>'f077');
$icons_set['fa']['fa-chevron-down'] = array("class"=>'fa',"tags"=>'chevron-down',"unicode"=>'f078');
$icons_set['fa']['fa-retweet'] = array("class"=>'fa',"tags"=>'retweet',"unicode"=>'f079');
$icons_set['fa']['fa-shopping-cart'] = array("class"=>'fa',"tags"=>'shopping-cart',"unicode"=>'f07a');
$icons_set['fa']['fa-folder'] = array("class"=>'fa',"tags"=>'folder',"unicode"=>'f07b');
$icons_set['fa']['fa-folder-open'] = array("class"=>'fa',"tags"=>'folder-open',"unicode"=>'f07c');
$icons_set['fa']['fa-arrows-v'] = array("class"=>'fa',"tags"=>'arrows-v',"unicode"=>'f07d');
$icons_set['fa']['fa-arrows-h'] = array("class"=>'fa',"tags"=>'arrows-h',"unicode"=>'f07e');
$icons_set['fa']['fa-bar-chart-o'] = array("class"=>'fa',"tags"=>'bar-chart-o',"unicode"=>'f080');
$icons_set['fa']['fa-twitter-square'] = array("class"=>'fa',"tags"=>'twitter-square',"unicode"=>'f081');
$icons_set['fa']['fa-facebook-square'] = array("class"=>'fa',"tags"=>'facebook-square',"unicode"=>'f082');
$icons_set['fa']['fa-camera-retro'] = array("class"=>'fa',"tags"=>'camera-retro',"unicode"=>'f083');
$icons_set['fa']['fa-key'] = array("class"=>'fa',"tags"=>'key',"unicode"=>'f084');
$icons_set['fa']['fa-gears'] = array("class"=>'fa',"tags"=>'gears',"unicode"=>'f085');
$icons_set['fa']['fa-cogs'] = array("class"=>'fa',"tags"=>'cogs',"unicode"=>'f085');
$icons_set['fa']['fa-comments'] = array("class"=>'fa',"tags"=>'comments',"unicode"=>'f086');
$icons_set['fa']['fa-thumbs-o-up'] = array("class"=>'fa',"tags"=>'thumbs-o-up',"unicode"=>'f087');
$icons_set['fa']['fa-thumbs-o-down'] = array("class"=>'fa',"tags"=>'thumbs-o-down',"unicode"=>'f088');
$icons_set['fa']['fa-star-half'] = array("class"=>'fa',"tags"=>'star-half',"unicode"=>'f089');
$icons_set['fa']['fa-heart-o'] = array("class"=>'fa',"tags"=>'heart-o',"unicode"=>'f08a');
$icons_set['fa']['fa-sign-out'] = array("class"=>'fa',"tags"=>'sign-out',"unicode"=>'f08b');
$icons_set['fa']['fa-linkedin-square'] = array("class"=>'fa',"tags"=>'linkedin-square',"unicode"=>'f08c');
$icons_set['fa']['fa-thumb-tack'] = array("class"=>'fa',"tags"=>'thumb-tack',"unicode"=>'f08d');
$icons_set['fa']['fa-external-link'] = array("class"=>'fa',"tags"=>'external-link',"unicode"=>'f08e');
$icons_set['fa']['fa-sign-in'] = array("class"=>'fa',"tags"=>'sign-in',"unicode"=>'f090');
$icons_set['fa']['fa-trophy'] = array("class"=>'fa',"tags"=>'trophy',"unicode"=>'f091');
$icons_set['fa']['fa-github-square'] = array("class"=>'fa',"tags"=>'github-square',"unicode"=>'f092');
$icons_set['fa']['fa-upload'] = array("class"=>'fa',"tags"=>'upload',"unicode"=>'f093');
$icons_set['fa']['fa-lemon-o'] = array("class"=>'fa',"tags"=>'lemon-o',"unicode"=>'f094');
$icons_set['fa']['fa-phone'] = array("class"=>'fa',"tags"=>'phone',"unicode"=>'f095');
$icons_set['fa']['fa-square-o'] = array("class"=>'fa',"tags"=>'square-o',"unicode"=>'f096');
$icons_set['fa']['fa-bookmark-o'] = array("class"=>'fa',"tags"=>'bookmark-o',"unicode"=>'f097');
$icons_set['fa']['fa-phone-square'] = array("class"=>'fa',"tags"=>'phone-square',"unicode"=>'f098');
$icons_set['fa']['fa-twitter'] = array("class"=>'fa',"tags"=>'twitter',"unicode"=>'f099');
$icons_set['fa']['fa-facebook'] = array("class"=>'fa',"tags"=>'facebook',"unicode"=>'f09a');
$icons_set['fa']['fa-github'] = array("class"=>'fa',"tags"=>'github',"unicode"=>'f09b');
$icons_set['fa']['fa-unlock'] = array("class"=>'fa',"tags"=>'unlock',"unicode"=>'f09c');
$icons_set['fa']['fa-credit-card'] = array("class"=>'fa',"tags"=>'credit-card',"unicode"=>'f09d');
$icons_set['fa']['fa-rss'] = array("class"=>'fa',"tags"=>'rss',"unicode"=>'f09e');
$icons_set['fa']['fa-hdd-o'] = array("class"=>'fa',"tags"=>'hdd-o',"unicode"=>'f0a0');
$icons_set['fa']['fa-bullhorn'] = array("class"=>'fa',"tags"=>'bullhorn',"unicode"=>'f0a1');
$icons_set['fa']['fa-bell'] = array("class"=>'fa',"tags"=>'bell',"unicode"=>'f0f3');
$icons_set['fa']['fa-certificate'] = array("class"=>'fa',"tags"=>'certificate',"unicode"=>'f0a3');
$icons_set['fa']['fa-hand-o-right'] = array("class"=>'fa',"tags"=>'hand-o-right',"unicode"=>'f0a4');
$icons_set['fa']['fa-hand-o-left'] = array("class"=>'fa',"tags"=>'hand-o-left',"unicode"=>'f0a5');
$icons_set['fa']['fa-hand-o-up'] = array("class"=>'fa',"tags"=>'hand-o-up',"unicode"=>'f0a6');
$icons_set['fa']['fa-hand-o-down'] = array("class"=>'fa',"tags"=>'hand-o-down',"unicode"=>'f0a7');
$icons_set['fa']['fa-arrow-circle-left'] = array("class"=>'fa',"tags"=>'arrow-circle-left',"unicode"=>'f0a8');
$icons_set['fa']['fa-arrow-circle-right'] = array("class"=>'fa',"tags"=>'arrow-circle-right',"unicode"=>'f0a9');
$icons_set['fa']['fa-arrow-circle-up'] = array("class"=>'fa',"tags"=>'arrow-circle-up',"unicode"=>'f0aa');
$icons_set['fa']['fa-arrow-circle-down'] = array("class"=>'fa',"tags"=>'arrow-circle-down',"unicode"=>'f0ab');
$icons_set['fa']['fa-globe'] = array("class"=>'fa',"tags"=>'globe',"unicode"=>'f0ac');
$icons_set['fa']['fa-wrench'] = array("class"=>'fa',"tags"=>'wrench',"unicode"=>'f0ad');
$icons_set['fa']['fa-tasks'] = array("class"=>'fa',"tags"=>'tasks',"unicode"=>'f0ae');
$icons_set['fa']['fa-filter'] = array("class"=>'fa',"tags"=>'filter',"unicode"=>'f0b0');
$icons_set['fa']['fa-briefcase'] = array("class"=>'fa',"tags"=>'briefcase',"unicode"=>'f0b1');
$icons_set['fa']['fa-arrows-alt'] = array("class"=>'fa',"tags"=>'arrows-alt',"unicode"=>'f0b2');
$icons_set['fa']['fa-group'] = array("class"=>'fa',"tags"=>'group',"unicode"=>'f0c0');
$icons_set['fa']['fa-users'] = array("class"=>'fa',"tags"=>'users',"unicode"=>'f0c0');
$icons_set['fa']['fa-chain'] = array("class"=>'fa',"tags"=>'chain',"unicode"=>'f0c1');
$icons_set['fa']['fa-link'] = array("class"=>'fa',"tags"=>'link',"unicode"=>'f0c1');
$icons_set['fa']['fa-cloud'] = array("class"=>'fa',"tags"=>'cloud',"unicode"=>'f0c2');
$icons_set['fa']['fa-flask'] = array("class"=>'fa',"tags"=>'flask',"unicode"=>'f0c3');
$icons_set['fa']['fa-cut'] = array("class"=>'fa',"tags"=>'cut',"unicode"=>'f0c4');
$icons_set['fa']['fa-scissors'] = array("class"=>'fa',"tags"=>'scissors',"unicode"=>'f0c4');
$icons_set['fa']['fa-copy'] = array("class"=>'fa',"tags"=>'copy',"unicode"=>'f0c5');
$icons_set['fa']['fa-files-o'] = array("class"=>'fa',"tags"=>'files-o',"unicode"=>'f0c5');
$icons_set['fa']['fa-paperclip'] = array("class"=>'fa',"tags"=>'paperclip',"unicode"=>'f0c6');
$icons_set['fa']['fa-save'] = array("class"=>'fa',"tags"=>'save',"unicode"=>'f0c7');
$icons_set['fa']['fa-floppy-o'] = array("class"=>'fa',"tags"=>'floppy-o',"unicode"=>'f0c7');
$icons_set['fa']['fa-square'] = array("class"=>'fa',"tags"=>'square',"unicode"=>'f0c8');
$icons_set['fa']['fa-bars'] = array("class"=>'fa',"tags"=>'bars',"unicode"=>'f0c9');
$icons_set['fa']['fa-list-ul'] = array("class"=>'fa',"tags"=>'list-ul',"unicode"=>'f0ca');
$icons_set['fa']['fa-list-ol'] = array("class"=>'fa',"tags"=>'list-ol',"unicode"=>'f0cb');
$icons_set['fa']['fa-strikethrough'] = array("class"=>'fa',"tags"=>'strikethrough',"unicode"=>'f0cc');
$icons_set['fa']['fa-underline'] = array("class"=>'fa',"tags"=>'underline',"unicode"=>'f0cd');
$icons_set['fa']['fa-table'] = array("class"=>'fa',"tags"=>'table',"unicode"=>'f0ce');
$icons_set['fa']['fa-magic'] = array("class"=>'fa',"tags"=>'magic',"unicode"=>'f0d0');
$icons_set['fa']['fa-truck'] = array("class"=>'fa',"tags"=>'truck',"unicode"=>'f0d1');
$icons_set['fa']['fa-pinterest'] = array("class"=>'fa',"tags"=>'pinterest',"unicode"=>'f0d2');
$icons_set['fa']['fa-pinterest-square'] = array("class"=>'fa',"tags"=>'pinterest-square',"unicode"=>'f0d3');
$icons_set['fa']['fa-google-plus-square'] = array("class"=>'fa',"tags"=>'google-plus-square',"unicode"=>'f0d4');
$icons_set['fa']['fa-google-plus'] = array("class"=>'fa',"tags"=>'google-plus',"unicode"=>'f0d5');
$icons_set['fa']['fa-money'] = array("class"=>'fa',"tags"=>'money',"unicode"=>'f0d6');
$icons_set['fa']['fa-caret-down'] = array("class"=>'fa',"tags"=>'caret-down',"unicode"=>'f0d7');
$icons_set['fa']['fa-caret-up'] = array("class"=>'fa',"tags"=>'caret-up',"unicode"=>'f0d8');
$icons_set['fa']['fa-caret-left'] = array("class"=>'fa',"tags"=>'caret-left',"unicode"=>'f0d9');
$icons_set['fa']['fa-caret-right'] = array("class"=>'fa',"tags"=>'caret-right',"unicode"=>'f0da');
$icons_set['fa']['fa-columns'] = array("class"=>'fa',"tags"=>'columns',"unicode"=>'f0db');
$icons_set['fa']['fa-unsorted'] = array("class"=>'fa',"tags"=>'unsorted',"unicode"=>'f0dc');
$icons_set['fa']['fa-sort'] = array("class"=>'fa',"tags"=>'sort',"unicode"=>'f0dc');
$icons_set['fa']['fa-sort-down'] = array("class"=>'fa',"tags"=>'sort-down',"unicode"=>'f0dd');
$icons_set['fa']['fa-sort-asc'] = array("class"=>'fa',"tags"=>'sort-asc',"unicode"=>'f0dd');
$icons_set['fa']['fa-sort-up'] = array("class"=>'fa',"tags"=>'sort-up',"unicode"=>'f0de');
$icons_set['fa']['fa-sort-desc'] = array("class"=>'fa',"tags"=>'sort-desc',"unicode"=>'f0de');
$icons_set['fa']['fa-envelope'] = array("class"=>'fa',"tags"=>'envelope',"unicode"=>'f0e0');
$icons_set['fa']['fa-linkedin'] = array("class"=>'fa',"tags"=>'linkedin',"unicode"=>'f0e1');
$icons_set['fa']['fa-rotate-left'] = array("class"=>'fa',"tags"=>'rotate-left',"unicode"=>'f0e2');
$icons_set['fa']['fa-undo'] = array("class"=>'fa',"tags"=>'undo',"unicode"=>'f0e2');
$icons_set['fa']['fa-legal'] = array("class"=>'fa',"tags"=>'legal',"unicode"=>'f0e3');
$icons_set['fa']['fa-gavel'] = array("class"=>'fa',"tags"=>'gavel',"unicode"=>'f0e3');
$icons_set['fa']['fa-dashboard'] = array("class"=>'fa',"tags"=>'dashboard',"unicode"=>'f0e4');
$icons_set['fa']['fa-tachometer'] = array("class"=>'fa',"tags"=>'tachometer',"unicode"=>'f0e4');
$icons_set['fa']['fa-comment-o'] = array("class"=>'fa',"tags"=>'comment-o',"unicode"=>'f0e5');
$icons_set['fa']['fa-comments-o'] = array("class"=>'fa',"tags"=>'comments-o',"unicode"=>'f0e6');
$icons_set['fa']['fa-flash'] = array("class"=>'fa',"tags"=>'flash',"unicode"=>'f0e7');
$icons_set['fa']['fa-bolt'] = array("class"=>'fa',"tags"=>'bolt',"unicode"=>'f0e7');
$icons_set['fa']['fa-sitemap'] = array("class"=>'fa',"tags"=>'sitemap',"unicode"=>'f0e8');
$icons_set['fa']['fa-umbrella'] = array("class"=>'fa',"tags"=>'umbrella',"unicode"=>'f0e9');
$icons_set['fa']['fa-paste'] = array("class"=>'fa',"tags"=>'paste',"unicode"=>'f0ea');
$icons_set['fa']['fa-clipboard'] = array("class"=>'fa',"tags"=>'clipboard',"unicode"=>'f0ea');
$icons_set['fa']['fa-lightbulb-o'] = array("class"=>'fa',"tags"=>'lightbulb-o',"unicode"=>'f0eb');
$icons_set['fa']['fa-exchange'] = array("class"=>'fa',"tags"=>'exchange',"unicode"=>'f0ec');
$icons_set['fa']['fa-cloud-download'] = array("class"=>'fa',"tags"=>'cloud-download',"unicode"=>'f0ed');
$icons_set['fa']['fa-cloud-upload'] = array("class"=>'fa',"tags"=>'cloud-upload',"unicode"=>'f0ee');
$icons_set['fa']['fa-user-md'] = array("class"=>'fa',"tags"=>'user-md',"unicode"=>'f0f0');
$icons_set['fa']['fa-stethoscope'] = array("class"=>'fa',"tags"=>'stethoscope',"unicode"=>'f0f1');
$icons_set['fa']['fa-suitcase'] = array("class"=>'fa',"tags"=>'suitcase',"unicode"=>'f0f2');
$icons_set['fa']['fa-bell-o'] = array("class"=>'fa',"tags"=>'bell-o',"unicode"=>'f0a2');
$icons_set['fa']['fa-coffee'] = array("class"=>'fa',"tags"=>'coffee',"unicode"=>'f0f4');
$icons_set['fa']['fa-cutlery'] = array("class"=>'fa',"tags"=>'cutlery',"unicode"=>'f0f5');
$icons_set['fa']['fa-file-text-o'] = array("class"=>'fa',"tags"=>'file-text-o',"unicode"=>'f0f6');
$icons_set['fa']['fa-building-o'] = array("class"=>'fa',"tags"=>'building-o',"unicode"=>'f0f7');
$icons_set['fa']['fa-hospital-o'] = array("class"=>'fa',"tags"=>'hospital-o',"unicode"=>'f0f8');
$icons_set['fa']['fa-ambulance'] = array("class"=>'fa',"tags"=>'ambulance',"unicode"=>'f0f9');
$icons_set['fa']['fa-medkit'] = array("class"=>'fa',"tags"=>'medkit',"unicode"=>'f0fa');
$icons_set['fa']['fa-fighter-jet'] = array("class"=>'fa',"tags"=>'fighter-jet',"unicode"=>'f0fb');
$icons_set['fa']['fa-beer'] = array("class"=>'fa',"tags"=>'beer',"unicode"=>'f0fc');
$icons_set['fa']['fa-h-square'] = array("class"=>'fa',"tags"=>'h-square',"unicode"=>'f0fd');
$icons_set['fa']['fa-plus-square'] = array("class"=>'fa',"tags"=>'plus-square',"unicode"=>'f0fe');
$icons_set['fa']['fa-angle-double-left'] = array("class"=>'fa',"tags"=>'angle-double-left',"unicode"=>'f100');
$icons_set['fa']['fa-angle-double-right'] = array("class"=>'fa',"tags"=>'angle-double-right',"unicode"=>'f101');
$icons_set['fa']['fa-angle-double-up'] = array("class"=>'fa',"tags"=>'angle-double-up',"unicode"=>'f102');
$icons_set['fa']['fa-angle-double-down'] = array("class"=>'fa',"tags"=>'angle-double-down',"unicode"=>'f103');
$icons_set['fa']['fa-angle-left'] = array("class"=>'fa',"tags"=>'angle-left',"unicode"=>'f104');
$icons_set['fa']['fa-angle-right'] = array("class"=>'fa',"tags"=>'angle-right',"unicode"=>'f105');
$icons_set['fa']['fa-angle-up'] = array("class"=>'fa',"tags"=>'angle-up',"unicode"=>'f106');
$icons_set['fa']['fa-angle-down'] = array("class"=>'fa',"tags"=>'angle-down',"unicode"=>'f107');
$icons_set['fa']['fa-desktop'] = array("class"=>'fa',"tags"=>'desktop',"unicode"=>'f108');
$icons_set['fa']['fa-laptop'] = array("class"=>'fa',"tags"=>'laptop',"unicode"=>'f109');
$icons_set['fa']['fa-tablet'] = array("class"=>'fa',"tags"=>'tablet',"unicode"=>'f10a');
$icons_set['fa']['fa-mobile-phone'] = array("class"=>'fa',"tags"=>'mobile-phone',"unicode"=>'f10b');
$icons_set['fa']['fa-mobile'] = array("class"=>'fa',"tags"=>'mobile',"unicode"=>'f10b');
$icons_set['fa']['fa-circle-o'] = array("class"=>'fa',"tags"=>'circle-o',"unicode"=>'f10c');
$icons_set['fa']['fa-quote-left'] = array("class"=>'fa',"tags"=>'quote-left',"unicode"=>'f10d');
$icons_set['fa']['fa-quote-right'] = array("class"=>'fa',"tags"=>'quote-right',"unicode"=>'f10e');
$icons_set['fa']['fa-spinner'] = array("class"=>'fa',"tags"=>'spinner',"unicode"=>'f110');
$icons_set['fa']['fa-circle'] = array("class"=>'fa',"tags"=>'circle',"unicode"=>'f111');
$icons_set['fa']['fa-mail-reply'] = array("class"=>'fa',"tags"=>'mail-reply',"unicode"=>'f112');
$icons_set['fa']['fa-reply'] = array("class"=>'fa',"tags"=>'reply',"unicode"=>'f112');
$icons_set['fa']['fa-github-alt'] = array("class"=>'fa',"tags"=>'github-alt',"unicode"=>'f113');
$icons_set['fa']['fa-folder-o'] = array("class"=>'fa',"tags"=>'folder-o',"unicode"=>'f114');
$icons_set['fa']['fa-folder-open-o'] = array("class"=>'fa',"tags"=>'folder-open-o',"unicode"=>'f115');
$icons_set['fa']['fa-smile-o'] = array("class"=>'fa',"tags"=>'smile-o',"unicode"=>'f118');
$icons_set['fa']['fa-frown-o'] = array("class"=>'fa',"tags"=>'frown-o',"unicode"=>'f119');
$icons_set['fa']['fa-meh-o'] = array("class"=>'fa',"tags"=>'meh-o',"unicode"=>'f11a');
$icons_set['fa']['fa-gamepad'] = array("class"=>'fa',"tags"=>'gamepad',"unicode"=>'f11b');
$icons_set['fa']['fa-keyboard-o'] = array("class"=>'fa',"tags"=>'keyboard-o',"unicode"=>'f11c');
$icons_set['fa']['fa-flag-o'] = array("class"=>'fa',"tags"=>'flag-o',"unicode"=>'f11d');
$icons_set['fa']['fa-flag-checkered'] = array("class"=>'fa',"tags"=>'flag-checkered',"unicode"=>'f11e');
$icons_set['fa']['fa-terminal'] = array("class"=>'fa',"tags"=>'terminal',"unicode"=>'f120');
$icons_set['fa']['fa-code'] = array("class"=>'fa',"tags"=>'code',"unicode"=>'f121');
$icons_set['fa']['fa-reply-all'] = array("class"=>'fa',"tags"=>'reply-all',"unicode"=>'f122');
$icons_set['fa']['fa-mail-reply-all'] = array("class"=>'fa',"tags"=>'mail-reply-all',"unicode"=>'f122');
$icons_set['fa']['fa-star-half-empty'] = array("class"=>'fa',"tags"=>'star-half-empty',"unicode"=>'f123');
$icons_set['fa']['fa-star-half-full'] = array("class"=>'fa',"tags"=>'star-half-full',"unicode"=>'f123');
$icons_set['fa']['fa-star-half-o'] = array("class"=>'fa',"tags"=>'star-half-o',"unicode"=>'f123');
$icons_set['fa']['fa-location-arrow'] = array("class"=>'fa',"tags"=>'location-arrow',"unicode"=>'f124');
$icons_set['fa']['fa-crop'] = array("class"=>'fa',"tags"=>'crop',"unicode"=>'f125');
$icons_set['fa']['fa-code-fork'] = array("class"=>'fa',"tags"=>'code-fork',"unicode"=>'f126');
$icons_set['fa']['fa-unlink'] = array("class"=>'fa',"tags"=>'unlink',"unicode"=>'f127');
$icons_set['fa']['fa-chain-broken'] = array("class"=>'fa',"tags"=>'chain-broken',"unicode"=>'f127');
$icons_set['fa']['fa-question'] = array("class"=>'fa',"tags"=>'question',"unicode"=>'f128');
$icons_set['fa']['fa-info'] = array("class"=>'fa',"tags"=>'info',"unicode"=>'f129');
$icons_set['fa']['fa-exclamation'] = array("class"=>'fa',"tags"=>'exclamation',"unicode"=>'f12a');
$icons_set['fa']['fa-superscript'] = array("class"=>'fa',"tags"=>'superscript',"unicode"=>'f12b');
$icons_set['fa']['fa-subscript'] = array("class"=>'fa',"tags"=>'subscript',"unicode"=>'f12c');
$icons_set['fa']['fa-eraser'] = array("class"=>'fa',"tags"=>'eraser',"unicode"=>'f12d');
$icons_set['fa']['fa-puzzle-piece'] = array("class"=>'fa',"tags"=>'puzzle-piece',"unicode"=>'f12e');
$icons_set['fa']['fa-microphone'] = array("class"=>'fa',"tags"=>'microphone',"unicode"=>'f130');
$icons_set['fa']['fa-microphone-slash'] = array("class"=>'fa',"tags"=>'microphone-slash',"unicode"=>'f131');
$icons_set['fa']['fa-shield'] = array("class"=>'fa',"tags"=>'shield',"unicode"=>'f132');
$icons_set['fa']['fa-calendar-o'] = array("class"=>'fa',"tags"=>'calendar-o',"unicode"=>'f133');
$icons_set['fa']['fa-fire-extinguisher'] = array("class"=>'fa',"tags"=>'fire-extinguisher',"unicode"=>'f134');
$icons_set['fa']['fa-rocket'] = array("class"=>'fa',"tags"=>'rocket',"unicode"=>'f135');
$icons_set['fa']['fa-maxcdn'] = array("class"=>'fa',"tags"=>'maxcdn',"unicode"=>'f136');
$icons_set['fa']['fa-chevron-circle-left'] = array("class"=>'fa',"tags"=>'chevron-circle-left',"unicode"=>'f137');
$icons_set['fa']['fa-chevron-circle-right'] = array("class"=>'fa',"tags"=>'chevron-circle-right',"unicode"=>'f138');
$icons_set['fa']['fa-chevron-circle-up'] = array("class"=>'fa',"tags"=>'chevron-circle-up',"unicode"=>'f139');
$icons_set['fa']['fa-chevron-circle-down'] = array("class"=>'fa',"tags"=>'chevron-circle-down',"unicode"=>'f13a');
$icons_set['fa']['fa-html5'] = array("class"=>'fa',"tags"=>'html5',"unicode"=>'f13b');
$icons_set['fa']['fa-css3'] = array("class"=>'fa',"tags"=>'css3',"unicode"=>'f13c');
$icons_set['fa']['fa-anchor'] = array("class"=>'fa',"tags"=>'anchor',"unicode"=>'f13d');
$icons_set['fa']['fa-unlock-alt'] = array("class"=>'fa',"tags"=>'unlock-alt',"unicode"=>'f13e');
$icons_set['fa']['fa-bullseye'] = array("class"=>'fa',"tags"=>'bullseye',"unicode"=>'f140');
$icons_set['fa']['fa-ellipsis-h'] = array("class"=>'fa',"tags"=>'ellipsis-h',"unicode"=>'f141');
$icons_set['fa']['fa-ellipsis-v'] = array("class"=>'fa',"tags"=>'ellipsis-v',"unicode"=>'f142');
$icons_set['fa']['fa-rss-square'] = array("class"=>'fa',"tags"=>'rss-square',"unicode"=>'f143');
$icons_set['fa']['fa-play-circle'] = array("class"=>'fa',"tags"=>'play-circle',"unicode"=>'f144');
$icons_set['fa']['fa-ticket'] = array("class"=>'fa',"tags"=>'ticket',"unicode"=>'f145');
$icons_set['fa']['fa-minus-square'] = array("class"=>'fa',"tags"=>'minus-square',"unicode"=>'f146');
$icons_set['fa']['fa-minus-square-o'] = array("class"=>'fa',"tags"=>'minus-square-o',"unicode"=>'f147');
$icons_set['fa']['fa-level-up'] = array("class"=>'fa',"tags"=>'level-up',"unicode"=>'f148');
$icons_set['fa']['fa-level-down'] = array("class"=>'fa',"tags"=>'level-down',"unicode"=>'f149');
$icons_set['fa']['fa-check-square'] = array("class"=>'fa',"tags"=>'check-square',"unicode"=>'f14a');
$icons_set['fa']['fa-pencil-square'] = array("class"=>'fa',"tags"=>'pencil-square',"unicode"=>'f14b');
$icons_set['fa']['fa-external-link-square'] = array("class"=>'fa',"tags"=>'external-link-square',"unicode"=>'f14c');
$icons_set['fa']['fa-share-square'] = array("class"=>'fa',"tags"=>'share-square',"unicode"=>'f14d');
$icons_set['fa']['fa-compass'] = array("class"=>'fa',"tags"=>'compass',"unicode"=>'f14e');
$icons_set['fa']['fa-toggle-down'] = array("class"=>'fa',"tags"=>'toggle-down',"unicode"=>'f150');
$icons_set['fa']['fa-caret-square-o-down'] = array("class"=>'fa',"tags"=>'caret-square-o-down',"unicode"=>'f151');
$icons_set['fa']['fa-toggle-right'] = array("class"=>'fa',"tags"=>'caret-square-o-down',"unicode"=>'f152');
$icons_set['fa']['fa-caret-square-o-right'] = array("class"=>'fa',"tags"=>'caret-square-o-down',"unicode"=>'f152');
$icons_set['fa']['fa-euro'] = array("class"=>'fa',"tags"=>'euro',"unicode"=>'f153');
$icons_set['fa']['fa-eur'] = array("class"=>'fa',"tags"=>'eur',"unicode"=>'f153');
$icons_set['fa']['fa-gbp'] = array("class"=>'fa',"tags"=>'gbp',"unicode"=>'f154');
$icons_set['fa']['fa-dollar'] = array("class"=>'fa',"tags"=>'dollar',"unicode"=>'f155');
$icons_set['fa']['fa-usd'] = array("class"=>'fa',"tags"=>'usd',"unicode"=>'f155');
$icons_set['fa']['fa-rupee'] = array("class"=>'fa',"tags"=>'rupee',"unicode"=>'f156');
$icons_set['fa']['fa-inr'] = array("class"=>'fa',"tags"=>'inr',"unicode"=>'f156');
$icons_set['fa']['fa-cny'] = array("class"=>'fa',"tags"=>'cny',"unicode"=>'f157');
$icons_set['fa']['fa-rmb'] = array("class"=>'fa',"tags"=>'rmb',"unicode"=>'f157');
$icons_set['fa']['fa-yen'] = array("class"=>'fa',"tags"=>'yen',"unicode"=>'f157');
$icons_set['fa']['fa-jpy'] = array("class"=>'fa',"tags"=>'jpy',"unicode"=>'f157');
$icons_set['fa']['fa-ruble'] = array("class"=>'fa',"tags"=>'ruble',"unicode"=>'f158');
$icons_set['fa']['fa-rouble'] = array("class"=>'fa',"tags"=>'rouble',"unicode"=>'f158');
$icons_set['fa']['fa-rub'] = array("class"=>'fa',"tags"=>'rub',"unicode"=>'f158');
$icons_set['fa']['fa-won'] = array("class"=>'fa',"tags"=>'won',"unicode"=>'f159');
$icons_set['fa']['fa-krw'] = array("class"=>'fa',"tags"=>'krw',"unicode"=>'f159');
$icons_set['fa']['fa-bitcoin'] = array("class"=>'fa',"tags"=>'bitcoin',"unicode"=>'f15a');
$icons_set['fa']['fa-btc'] = array("class"=>'fa',"tags"=>'btc',"unicode"=>'f15a');
$icons_set['fa']['fa-file'] = array("class"=>'fa',"tags"=>'file',"unicode"=>'f15b');
$icons_set['fa']['fa-file-text'] = array("class"=>'fa',"tags"=>'file-text',"unicode"=>'f15c');
$icons_set['fa']['fa-sort-alpha-asc'] = array("class"=>'fa',"tags"=>'sort-alpha-asc',"unicode"=>'f15d');
$icons_set['fa']['fa-sort-alpha-desc'] = array("class"=>'fa',"tags"=>'sort-alpha-desc',"unicode"=>'f15e');
$icons_set['fa']['fa-sort-amount-asc'] = array("class"=>'fa',"tags"=>'sort-amount-asc',"unicode"=>'f160');
$icons_set['fa']['fa-sort-amount-desc'] = array("class"=>'fa',"tags"=>'sort-amount-desc',"unicode"=>'f161');
$icons_set['fa']['fa-sort-numeric-asc'] = array("class"=>'fa',"tags"=>'sort-numeric-asc',"unicode"=>'f162');
$icons_set['fa']['fa-sort-numeric-desc'] = array("class"=>'fa',"tags"=>'sort-numeric-desc',"unicode"=>'f163');
$icons_set['fa']['fa-thumbs-up'] = array("class"=>'fa',"tags"=>'thumbs-up',"unicode"=>'f164');
$icons_set['fa']['fa-thumbs-down'] = array("class"=>'fa',"tags"=>'thumbs-down',"unicode"=>'f165');
$icons_set['fa']['fa-youtube-square'] = array("class"=>'fa',"tags"=>'youtube-square',"unicode"=>'f166');
$icons_set['fa']['fa-youtube'] = array("class"=>'fa',"tags"=>'youtube',"unicode"=>'f167');
$icons_set['fa']['fa-xing'] = array("class"=>'fa',"tags"=>'xing',"unicode"=>'f168');
$icons_set['fa']['fa-xing-square'] = array("class"=>'fa',"tags"=>'xing-square',"unicode"=>'f169');
$icons_set['fa']['fa-youtube-play'] = array("class"=>'fa',"tags"=>'youtube-play',"unicode"=>'f16a');
$icons_set['fa']['fa-dropbox'] = array("class"=>'fa',"tags"=>'dropbox',"unicode"=>'f16b');
$icons_set['fa']['fa-stack-overflow'] = array("class"=>'fa',"tags"=>'stack-overflow',"unicode"=>'f16c');
$icons_set['fa']['fa-instagram'] = array("class"=>'fa',"tags"=>'instagram',"unicode"=>'f16d');
$icons_set['fa']['fa-flickr'] = array("class"=>'fa',"tags"=>'flickr',"unicode"=>'f16e');
$icons_set['fa']['fa-adn'] = array("class"=>'fa',"tags"=>'adn',"unicode"=>'f170');
$icons_set['fa']['fa-bitbucket'] = array("class"=>'fa',"tags"=>'bitbucket',"unicode"=>'f171');
$icons_set['fa']['fa-bitbucket-square'] = array("class"=>'fa',"tags"=>'bitbucket-square',"unicode"=>'f172');
$icons_set['fa']['fa-tumblr'] = array("class"=>'fa',"tags"=>'tumblr',"unicode"=>'f173');
$icons_set['fa']['fa-tumblr-square'] = array("class"=>'fa',"tags"=>'tumblr-square',"unicode"=>'f174');
$icons_set['fa']['fa-long-arrow-down'] = array("class"=>'fa',"tags"=>'long-arrow-down',"unicode"=>'f175');
$icons_set['fa']['fa-long-arrow-up'] = array("class"=>'fa',"tags"=>'long-arrow-up',"unicode"=>'f176');
$icons_set['fa']['fa-long-arrow-left'] = array("class"=>'fa',"tags"=>'long-arrow-left',"unicode"=>'f177');
$icons_set['fa']['fa-long-arrow-right'] = array("class"=>'fa',"tags"=>'long-arrow-right',"unicode"=>'f178');
$icons_set['fa']['fa-apple'] = array("class"=>'fa',"tags"=>'apple',"unicode"=>'f179');
$icons_set['fa']['fa-windows'] = array("class"=>'fa',"tags"=>'windows',"unicode"=>'f17a');
$icons_set['fa']['fa-android'] = array("class"=>'fa',"tags"=>'android',"unicode"=>'f17b');
$icons_set['fa']['fa-linux'] = array("class"=>'fa',"tags"=>'linux',"unicode"=>'f17c');
$icons_set['fa']['fa-dribbble'] = array("class"=>'fa',"tags"=>'dribbble',"unicode"=>'f17d');
$icons_set['fa']['fa-skype'] = array("class"=>'fa',"tags"=>'skype',"unicode"=>'f17e');
$icons_set['fa']['fa-foursquare'] = array("class"=>'fa',"tags"=>'foursquare',"unicode"=>'f180');
$icons_set['fa']['fa-trello'] = array("class"=>'fa',"tags"=>'trello',"unicode"=>'f181');
$icons_set['fa']['fa-female'] = array("class"=>'fa',"tags"=>'female',"unicode"=>'f182');
$icons_set['fa']['fa-male'] = array("class"=>'fa',"tags"=>'male',"unicode"=>'f183');
$icons_set['fa']['fa-gittip'] = array("class"=>'fa',"tags"=>'gittip',"unicode"=>'f184');
$icons_set['fa']['fa-sun-o'] = array("class"=>'fa',"tags"=>'sun-o',"unicode"=>'f185');
$icons_set['fa']['fa-moon-o'] = array("class"=>'fa',"tags"=>'moon-o',"unicode"=>'f186');
$icons_set['fa']['fa-archive'] = array("class"=>'fa',"tags"=>'archive',"unicode"=>'f187');
$icons_set['fa']['fa-bug'] = array("class"=>'fa',"tags"=>'bug',"unicode"=>'f188');
$icons_set['fa']['fa-vk'] = array("class"=>'fa',"tags"=>'vk',"unicode"=>'f189');
$icons_set['fa']['fa-weibo'] = array("class"=>'fa',"tags"=>'weibo',"unicode"=>'f18a');
$icons_set['fa']['fa-renren'] = array("class"=>'fa',"tags"=>'renren',"unicode"=>'f18b');
$icons_set['fa']['fa-pagelines'] = array("class"=>'fa',"tags"=>'pagelines',"unicode"=>'f18c');
$icons_set['fa']['fa-stack-exchange'] = array("class"=>'fa',"tags"=>'stack-exchange',"unicode"=>'f18d');
$icons_set['fa']['fa-arrow-circle-o-right'] = array("class"=>'fa',"tags"=>'arrow-circle-o-right',"unicode"=>'f18e');
$icons_set['fa']['fa-arrow-circle-o-left'] = array("class"=>'fa',"tags"=>'arrow-circle-o-left',"unicode"=>'f190');
$icons_set['fa']['fa-toggle-left'] = array("class"=>'fa',"tags"=>'toggle-left',"unicode"=>'f191');
$icons_set['fa']['fa-caret-square-o-left'] = array("class"=>'fa',"tags"=>'caret-square-o-left',"unicode"=>'f191');
$icons_set['fa']['fa-dot-circle-o'] = array("class"=>'fa',"tags"=>'dot-circle-o',"unicode"=>'f192');
$icons_set['fa']['fa-wheelchair'] = array("class"=>'fa',"tags"=>'wheelchair',"unicode"=>'f193');
$icons_set['fa']['fa-vimeo-square'] = array("class"=>'fa',"tags"=>'vimeo-square',"unicode"=>'f194');
$icons_set['fa']['fa-turkish-lira'] = array("class"=>'fa',"tags"=>'turkish-lira',"unicode"=>'f195');
$icons_set['fa']['fa-try'] = array("class"=>'fa',"tags"=>'try',"unicode"=>'f195');
$icons_set['fa']['fa-plus-square-o'] = array("class"=>'fa',"tags"=>'plus-square-o',"unicode"=>'f196');

/* OUTLINE ICONS SET*/
$icons_set['outline']['outline-yoga'] = array("class"=>'outline', "tags"=>'yoga',"unicode"=>'e600');
$icons_set['outline']['outline-world-times'] = array("class"=>'outline', "tags"=>'world-times',"unicode"=>'e601');
$icons_set['outline']['outline-winners-podium'] = array("class"=>'outline', "tags"=>'winners-podium',"unicode"=>'e602');
$icons_set['outline']['outline-wine-glass'] = array("class"=>'outline', "tags"=>'wine-glass',"unicode"=>'e603');
$icons_set['outline']['outline-weight-lifting'] = array("class"=>'outline', "tags"=>'weight-lifting',"unicode"=>'e604');
$icons_set['outline']['outline-water-volleyball'] = array("class"=>'outline', "tags"=>'water-volleyball',"unicode"=>'e605');
$icons_set['outline']['outline-warning'] = array("class"=>'outline', "tags"=>'warning',"unicode"=>'e606');
$icons_set['outline']['outline-wardrobe'] = array("class"=>'outline', "tags"=>'wardrobe',"unicode"=>'e607');
$icons_set['outline']['outline-walking'] = array("class"=>'outline', "tags"=>'walking',"unicode"=>'e608');
$icons_set['outline']['outline-volume-mute'] = array("class"=>'outline', "tags"=>'volume-mute',"unicode"=>'e609');
$icons_set['outline']['outline-volume-middle'] = array("class"=>'outline', "tags"=>'volume-middle',"unicode"=>'e60a');
$icons_set['outline']['outline-volume-low'] = array("class"=>'outline', "tags"=>'volume-low',"unicode"=>'e60b');
$icons_set['outline']['outline-volume-high'] = array("class"=>'outline', "tags"=>'volume-high',"unicode"=>'e60c');
$icons_set['outline']['outline-volleyball'] = array("class"=>'outline', "tags"=>'volleyball',"unicode"=>'e60d');
$icons_set['outline']['outline-vertical-slider'] = array("class"=>'outline', "tags"=>'vertical-slider',"unicode"=>'e60e');
$icons_set['outline']['outline-venn-diagram'] = array("class"=>'outline', "tags"=>'venn-diagram',"unicode"=>'e60f');
$icons_set['outline']['outline-user'] = array("class"=>'outline', "tags"=>'user',"unicode"=>'e610');
$icons_set['outline']['outline-user-tick'] = array("class"=>'outline', "tags"=>'user-tick',"unicode"=>'e611');
$icons_set['outline']['outline-user-remove'] = array("class"=>'outline', "tags"=>'user-remove',"unicode"=>'e612');
$icons_set['outline']['outline-user-delete'] = array("class"=>'outline', "tags"=>'user-delete',"unicode"=>'e613');
$icons_set['outline']['outline-user-add'] = array("class"=>'outline', "tags"=>'user-add',"unicode"=>'e614');
$icons_set['outline']['outline-upload'] = array("class"=>'outline', "tags"=>'upload',"unicode"=>'e615');
$icons_set['outline']['outline-umbrella'] = array("class"=>'outline', "tags"=>'umbrella',"unicode"=>'e616');
$icons_set['outline']['outline-tv'] = array("class"=>'outline', "tags"=>'tv',"unicode"=>'e617');
$icons_set['outline']['outline-trophy-star'] = array("class"=>'outline', "tags"=>'trophy-star',"unicode"=>'e618');
$icons_set['outline']['outline-trash'] = array("class"=>'outline', "tags"=>'trash',"unicode"=>'e619');
$icons_set['outline']['outline-top-charts'] = array("class"=>'outline', "tags"=>'top-charts',"unicode"=>'e62a');
$icons_set['outline']['outline-timer'] = array("class"=>'outline', "tags"=>'timer',"unicode"=>'e62b');
$icons_set['outline']['outline-tennis'] = array("class"=>'outline', "tags"=>'tennis',"unicode"=>'e62c');
$icons_set['outline']['outline-tennis-ball'] = array("class"=>'outline', "tags"=>'tennis-ball',"unicode"=>'e62d');
$icons_set['outline']['outline-television'] = array("class"=>'outline', "tags"=>'television',"unicode"=>'e62e');
$icons_set['outline']['outline-telephone'] = array("class"=>'outline', "tags"=>'telephone',"unicode"=>'e62f');
$icons_set['outline']['outline-tea-cup'] = array("class"=>'outline', "tags"=>'tea-cup',"unicode"=>'e620');
$icons_set['outline']['outline-target'] = array("class"=>'outline', "tags"=>'target',"unicode"=>'e621');
$icons_set['outline']['outline-tag'] = array("class"=>'outline', "tags"=>'tag',"unicode"=>'e622');
$icons_set['outline']['outline-tag-yen-yuan'] = array("class"=>'outline', "tags"=>'tag-yen-yuan',"unicode"=>'e623');
$icons_set['outline']['outline-tag-rupee'] = array("class"=>'outline', "tags"=>'tag-rupee',"unicode"=>'e624');
$icons_set['outline']['outline-tag-pound'] = array("class"=>'outline', "tags"=>'tag-pound',"unicode"=>'e625');
$icons_set['outline']['outline-tag-euro'] = array("class"=>'outline', "tags"=>'tag-euro',"unicode"=>'e626');
$icons_set['outline']['outline-tag-dollar'] = array("class"=>'outline', "tags"=>'tag-dollar',"unicode"=>'e627');
$icons_set['outline']['outline-tablet'] = array("class"=>'outline', "tags"=>'tablet',"unicode"=>'e628');
$icons_set['outline']['outline-syncing'] = array("class"=>'outline', "tags"=>'syncing',"unicode"=>'e629');
$icons_set['outline']['outline-swimming'] = array("class"=>'outline', "tags"=>'swimming',"unicode"=>'e62a');
$icons_set['outline']['outline-sun-cloud'] = array("class"=>'outline', "tags"=>'sun-cloud',"unicode"=>'e62b');
$icons_set['outline']['outline-stroller'] = array("class"=>'outline', "tags"=>'stroller',"unicode"=>'e62c');
$icons_set['outline']['outline-stretching'] = array("class"=>'outline', "tags"=>'stretching',"unicode"=>'e62d');
$icons_set['outline']['outline-stopwatch'] = array("class"=>'outline', "tags"=>'stopwatch',"unicode"=>'e62e');
$icons_set['outline']['outline-steering-wheel'] = array("class"=>'outline', "tags"=>'steering-wheel',"unicode"=>'e62f');
$icons_set['outline']['outline-start'] = array("class"=>'outline', "tags"=>'start',"unicode"=>'e630');
$icons_set['outline']['outline-star-jumps'] = array("class"=>'outline', "tags"=>'star-jumps',"unicode"=>'e631');
$icons_set['outline']['outline-square-root'] = array("class"=>'outline', "tags"=>'square-root',"unicode"=>'e632');
$icons_set['outline']['outline-square-brackets'] = array("class"=>'outline', "tags"=>'square-brackets',"unicode"=>'e633');
$icons_set['outline']['outline-sprinting'] = array("class"=>'outline', "tags"=>'sprinting',"unicode"=>'e634');
$icons_set['outline']['outline-sprint-cycling'] = array("class"=>'outline', "tags"=>'sprint-cycling',"unicode"=>'e635');
$icons_set['outline']['outline-speedometer'] = array("class"=>'outline', "tags"=>'speedometer',"unicode"=>'e636');
$icons_set['outline']['outline-spanner'] = array("class"=>'outline', "tags"=>'spanner',"unicode"=>'e637');
$icons_set['outline']['outline-sofa'] = array("class"=>'outline', "tags"=>'sofa',"unicode"=>'e638');
$icons_set['outline']['outline-sofa-bed'] = array("class"=>'outline', "tags"=>'sofa-bed',"unicode"=>'e639');
$icons_set['outline']['outline-soccer-player'] = array("class"=>'outline', "tags"=>'soccer-player',"unicode"=>'e63a');
$icons_set['outline']['outline-soccer-ball'] = array("class"=>'outline', "tags"=>'soccer-ball',"unicode"=>'e63b');
$icons_set['outline']['outline-snowflake'] = array("class"=>'outline', "tags"=>'snowflake',"unicode"=>'e63c');
$icons_set['outline']['outline-smartphone-shake'] = array("class"=>'outline', "tags"=>'smartphone-shake',"unicode"=>'e63d');
$icons_set['outline']['outline-smartphone-outgoing'] = array("class"=>'outline', "tags"=>'smartphone-outgoing',"unicode"=>'e63e');
$icons_set['outline']['outline-smartphone-incoming'] = array("class"=>'outline', "tags"=>'smartphone-incoming',"unicode"=>'e63f');
$icons_set['outline']['outline-smartphone-flip'] = array("class"=>'outline', "tags"=>'smartphone-flip',"unicode"=>'e640');
$icons_set['outline']['outline-smartphone-change-orientation'] = array("class"=>'outline', "tags"=>'smartphone-change-orientation',"unicode"=>'e641');
$icons_set['outline']['outline-smartphone-calibrate-location'] = array("class"=>'outline', "tags"=>'smartphone-calibrate-location',"unicode"=>'e642');
$icons_set['outline']['outline-skipping'] = array("class"=>'outline', "tags"=>'skipping',"unicode"=>'e643');
$icons_set['outline']['outline-skiing'] = array("class"=>'outline', "tags"=>'skiing',"unicode"=>'e644');
$icons_set['outline']['outline-skateboarder'] = array("class"=>'outline', "tags"=>'skateboarder',"unicode"=>'e645');
$icons_set['outline']['outline-signposts'] = array("class"=>'outline', "tags"=>'signposts',"unicode"=>'e646');
$icons_set['outline']['outline-signpost'] = array("class"=>'outline', "tags"=>'signpost',"unicode"=>'e647');
$icons_set['outline']['outline-side-table'] = array("class"=>'outline', "tags"=>'side-table',"unicode"=>'e648');
$icons_set['outline']['outline-side-drawers'] = array("class"=>'outline', "tags"=>'side-drawers',"unicode"=>'e649');
$icons_set['outline']['outline-shuffle'] = array("class"=>'outline', "tags"=>'shuffle',"unicode"=>'e64a');
$icons_set['outline']['outline-shredder'] = array("class"=>'outline', "tags"=>'shredder',"unicode"=>'e64b');
$icons_set['outline']['outline-shopping-cart'] = array("class"=>'outline', "tags"=>'shopping-cart',"unicode"=>'e64c');
$icons_set['outline']['outline-shopping-cart-remove-item'] = array("class"=>'outline', "tags"=>'shopping-cart-remove-item',"unicode"=>'e64d');
$icons_set['outline']['outline-shopping-cart-add-item'] = array("class"=>'outline', "tags"=>'shopping-cart-add-item',"unicode"=>'e64e');
$icons_set['outline']['outline-shopping-basket'] = array("class"=>'outline', "tags"=>'shopping-basket',"unicode"=>'e64f');
$icons_set['outline']['outline-shopping-basket-tic'] = array("class"=>'outline', "tags"=>'shopping-basket-tic',"unicode"=>'e650');
$icons_set['outline']['outline-shopping-basket-remove'] = array("class"=>'outline', "tags"=>'shopping-basket-remove',"unicode"=>'e651');
$icons_set['outline']['outline-shopping-basket-delete'] = array("class"=>'outline', "tags"=>'shopping-basket-delete',"unicode"=>'e652');
$icons_set['outline']['outline-shopping-basket-add'] = array("class"=>'outline', "tags"=>'shopping-basket-add',"unicode"=>'e653');
$icons_set['outline']['outline-shopping-bag'] = array("class"=>'outline', "tags"=>'shopping-bag',"unicode"=>'e654');
$icons_set['outline']['outline-shield'] = array("class"=>'outline', "tags"=>'shield',"unicode"=>'e655');
$icons_set['outline']['outline-search'] = array("class"=>'outline', "tags"=>'search',"unicode"=>'e656');
$icons_set['outline']['outline-scroll'] = array("class"=>'outline', "tags"=>'scroll',"unicode"=>'e657');
$icons_set['outline']['outline-satchel'] = array("class"=>'outline', "tags"=>'satchel',"unicode"=>'e658');
$icons_set['outline']['outline-safe'] = array("class"=>'outline', "tags"=>'safe',"unicode"=>'e659');
$icons_set['outline']['outline-sad-face'] = array("class"=>'outline', "tags"=>'sad-face',"unicode"=>'e65a');
$icons_set['outline']['outline-rupee'] = array("class"=>'outline', "tags"=>'rupee',"unicode"=>'e65b');
$icons_set['outline']['outline-running'] = array("class"=>'outline', "tags"=>'running',"unicode"=>'e65c');
$icons_set['outline']['outline-rss'] = array("class"=>'outline', "tags"=>'rss',"unicode"=>'e65d');
$icons_set['outline']['outline-roller-blading'] = array("class"=>'outline', "tags"=>'roller-blading',"unicode"=>'e65e');
$icons_set['outline']['outline-rocket'] = array("class"=>'outline', "tags"=>'rocket',"unicode"=>'e65f');
$icons_set['outline']['outline-rewind'] = array("class"=>'outline', "tags"=>'rewind',"unicode"=>'e660');
$icons_set['outline']['outline-reverse'] = array("class"=>'outline', "tags"=>'reverse',"unicode"=>'e661');
$icons_set['outline']['outline-reverse-arrow'] = array("class"=>'outline', "tags"=>'reverse-arrow',"unicode"=>'e662');
$icons_set['outline']['outline-resume'] = array("class"=>'outline', "tags"=>'resume',"unicode"=>'e663');
$icons_set['outline']['outline-reset'] = array("class"=>'outline', "tags"=>'reset',"unicode"=>'e664');
$icons_set['outline']['outline-reply'] = array("class"=>'outline', "tags"=>'reply',"unicode"=>'e665');
$icons_set['outline']['outline-recents'] = array("class"=>'outline', "tags"=>'recents',"unicode"=>'e666');
$icons_set['outline']['outline-question-mark'] = array("class"=>'outline', "tags"=>'question-mark',"unicode"=>'e667');
$icons_set['outline']['outline-printer'] = array("class"=>'outline', "tags"=>'printer',"unicode"=>'e668');
$icons_set['outline']['outline-price-tags'] = array("class"=>'outline', "tags"=>'price-tags',"unicode"=>'e669');
$icons_set['outline']['outline-previous'] = array("class"=>'outline', "tags"=>'previous',"unicode"=>'e66a');
$icons_set['outline']['outline-presentation'] = array("class"=>'outline', "tags"=>'presentation',"unicode"=>'e66b');
$icons_set['outline']['outline-power'] = array("class"=>'outline', "tags"=>'power',"unicode"=>'e66c');
$icons_set['outline']['outline-pound-sterling'] = array("class"=>'outline', "tags"=>'pound-sterling',"unicode"=>'e66d');
$icons_set['outline']['outline-pool-8-ball'] = array("class"=>'outline', "tags"=>'pool-8-ball',"unicode"=>'e66e');
$icons_set['outline']['outline-plus'] = array("class"=>'outline', "tags"=>'plus',"unicode"=>'e66f');
$icons_set['outline']['outline-plus-minus'] = array("class"=>'outline', "tags"=>'plus-minus',"unicode"=>'e670');
$icons_set['outline']['outline-playlists'] = array("class"=>'outline', "tags"=>'playlists',"unicode"=>'e671');
$icons_set['outline']['outline-play'] = array("class"=>'outline', "tags"=>'play',"unicode"=>'e672');
$icons_set['outline']['outline-play-tv'] = array("class"=>'outline', "tags"=>'play-tv',"unicode"=>'e673');
$icons_set['outline']['outline-pin'] = array("class"=>'outline', "tags"=>'pin',"unicode"=>'e674');
$icons_set['outline']['outline-pilates'] = array("class"=>'outline', "tags"=>'pilates',"unicode"=>'e675');
$icons_set['outline']['outline-piggy-bank'] = array("class"=>'outline', "tags"=>'piggy-bank',"unicode"=>'e676');
$icons_set['outline']['outline-pie-chart'] = array("class"=>'outline', "tags"=>'pie-chart',"unicode"=>'e677');
$icons_set['outline']['outline-picture-mountains'] = array("class"=>'outline', "tags"=>'picture-mountains',"unicode"=>'e678');
$icons_set['outline']['outline-picture-ios'] = array("class"=>'outline', "tags"=>'picture-ios',"unicode"=>'e679');
$icons_set['outline']['outline-picture-frame-ios'] = array("class"=>'outline', "tags"=>'picture-frame-ios',"unicode"=>'e67a');
$icons_set['outline']['outline-picture-fields'] = array("class"=>'outline', "tags"=>'picture-fields',"unicode"=>'e67b');
$icons_set['outline']['outline-photos'] = array("class"=>'outline', "tags"=>'photos',"unicode"=>'e67c');
$icons_set['outline']['outline-percentage'] = array("class"=>'outline', "tags"=>'percentage',"unicode"=>'e67d');
$icons_set['outline']['outline-pencil'] = array("class"=>'outline', "tags"=>'pencil',"unicode"=>'e67e');
$icons_set['outline']['outline-paw-print'] = array("class"=>'outline', "tags"=>'paw-print',"unicode"=>'e67f');
$icons_set['outline']['outline-pause'] = array("class"=>'outline', "tags"=>'pause',"unicode"=>'e680');
$icons_set['outline']['outline-past'] = array("class"=>'outline', "tags"=>'past',"unicode"=>'e681');
$icons_set['outline']['outline-paperclip'] = array("class"=>'outline', "tags"=>'paperclip',"unicode"=>'e682');
$icons_set['outline']['outline-palette'] = array("class"=>'outline', "tags"=>'palette',"unicode"=>'e683');
$icons_set['outline']['outline-paint-tin'] = array("class"=>'outline', "tags"=>'paint-tin',"unicode"=>'e684');
$icons_set['outline']['outline-paint-roller'] = array("class"=>'outline', "tags"=>'paint-roller',"unicode"=>'e685');
$icons_set['outline']['outline-padlock-open'] = array("class"=>'outline', "tags"=>'padlock-open',"unicode"=>'e686');
$icons_set['outline']['outline-padlock-closed'] = array("class"=>'outline', "tags"=>'padlock-closed',"unicode"=>'e687');
$icons_set['outline']['outline-origami'] = array("class"=>'outline', "tags"=>'origami',"unicode"=>'e688');
$icons_set['outline']['outline-orange-half'] = array("class"=>'outline', "tags"=>'orange-half',"unicode"=>'e689');
$icons_set['outline']['outline-opposite-vertical-arrows'] = array("class"=>'outline', "tags"=>'opposite-vertical-arrows',"unicode"=>'e68a');
$icons_set['outline']['outline-number'] = array("class"=>'outline', "tags"=>'number',"unicode"=>'e68b');
$icons_set['outline']['outline-num-9'] = array("class"=>'outline', "tags"=>'num-9',"unicode"=>'e68c');
$icons_set['outline']['outline-num-8'] = array("class"=>'outline', "tags"=>'num-8',"unicode"=>'e68d');
$icons_set['outline']['outline-num-7'] = array("class"=>'outline', "tags"=>'num-7',"unicode"=>'e68e');
$icons_set['outline']['outline-num-6'] = array("class"=>'outline', "tags"=>'num-6',"unicode"=>'e68f');
$icons_set['outline']['outline-num-5'] = array("class"=>'outline', "tags"=>'num-5',"unicode"=>'e690');
$icons_set['outline']['outline-num-4'] = array("class"=>'outline', "tags"=>'num-4',"unicode"=>'e691');
$icons_set['outline']['outline-num-3'] = array("class"=>'outline', "tags"=>'num-3',"unicode"=>'e692');
$icons_set['outline']['outline-num-2'] = array("class"=>'outline', "tags"=>'num-2',"unicode"=>'e693');
$icons_set['outline']['outline-num-1'] = array("class"=>'outline', "tags"=>'num-1',"unicode"=>'e694');
$icons_set['outline']['outline-num-0'] = array("class"=>'outline', "tags"=>'num-0',"unicode"=>'e695');
$icons_set['outline']['outline-notes-yen-yuan'] = array("class"=>'outline', "tags"=>'notes-yen-yuan',"unicode"=>'e696');
$icons_set['outline']['outline-notes-rupee'] = array("class"=>'outline', "tags"=>'notes-rupee',"unicode"=>'e697');
$icons_set['outline']['outline-notes-pound'] = array("class"=>'outline', "tags"=>'notes-pound',"unicode"=>'e698');
$icons_set['outline']['outline-notes-euro'] = array("class"=>'outline', "tags"=>'notes-euro',"unicode"=>'e699');
$icons_set['outline']['outline-notes-dollar'] = array("class"=>'outline', "tags"=>'notes-dollar',"unicode"=>'e69a');
$icons_set['outline']['outline-notepad'] = array("class"=>'outline', "tags"=>'notepad',"unicode"=>'e69b');
$icons_set['outline']['outline-notebook'] = array("class"=>'outline', "tags"=>'notebook',"unicode"=>'e69c');
$icons_set['outline']['outline-not-equal-to'] = array("class"=>'outline', "tags"=>'not-equal-to',"unicode"=>'e69d');
$icons_set['outline']['outline-next'] = array("class"=>'outline', "tags"=>'next',"unicode"=>'e69e');
$icons_set['outline']['outline-newspaper'] = array("class"=>'outline', "tags"=>'newspaper',"unicode"=>'e69f');
$icons_set['outline']['outline-new'] = array("class"=>'outline', "tags"=>'new',"unicode"=>'e6a0');
$icons_set['outline']['outline-network-tree'] = array("class"=>'outline', "tags"=>'network-tree',"unicode"=>'e6a1');
$icons_set['outline']['outline-network-line'] = array("class"=>'outline', "tags"=>'network-line',"unicode"=>'e6a2');
$icons_set['outline']['outline-network-closed'] = array("class"=>'outline', "tags"=>'network-closed',"unicode"=>'e6a3');
$icons_set['outline']['outline-near-me'] = array("class"=>'outline', "tags"=>'near-me',"unicode"=>'e6a4');
$icons_set['outline']['outline-music'] = array("class"=>'outline', "tags"=>'music',"unicode"=>'e6a5');
$icons_set['outline']['outline-multiply'] = array("class"=>'outline', "tags"=>'multiply',"unicode"=>'e6a6');
$icons_set['outline']['outline-movies'] = array("class"=>'outline', "tags"=>'movies',"unicode"=>'e6a7');
$icons_set['outline']['outline-mortar-board'] = array("class"=>'outline', "tags"=>'mortar-board',"unicode"=>'e6a8');
$icons_set['outline']['outline-more-than'] = array("class"=>'outline', "tags"=>'more-than',"unicode"=>'e6a9');
$icons_set['outline']['outline-more-than-or-equal'] = array("class"=>'outline', "tags"=>'more-than-or-equal',"unicode"=>'e6aa');
$icons_set['outline']['outline-moon'] = array("class"=>'outline', "tags"=>'moon',"unicode"=>'e6ab');
$icons_set['outline']['outline-mobile'] = array("class"=>'outline', "tags"=>'mobile',"unicode"=>'e6ac');
$icons_set['outline']['outline-mobile-tv'] = array("class"=>'outline', "tags"=>'mobile-tv',"unicode"=>'e6ad');
$icons_set['outline']['outline-mobile-signal'] = array("class"=>'outline', "tags"=>'mobile-signal',"unicode"=>'e6ae');
$icons_set['outline']['outline-mobile-mobile'] = array("class"=>'outline', "tags"=>'mobile-mobile',"unicode"=>'e6af');
$icons_set['outline']['outline-mobile-computer'] = array("class"=>'outline', "tags"=>'mobile-computer',"unicode"=>'e6b0');
$icons_set['outline']['outline-minus'] = array("class"=>'outline', "tags"=>'minus',"unicode"=>'e6b1');
$icons_set['outline']['outline-microphone'] = array("class"=>'outline', "tags"=>'microphone',"unicode"=>'e6b2');
$icons_set['outline']['outline-megaphone'] = array("class"=>'outline', "tags"=>'megaphone',"unicode"=>'e6b3');
$icons_set['outline']['outline-medical-kit'] = array("class"=>'outline', "tags"=>'medical-kit',"unicode"=>'e6b4');
$icons_set['outline']['outline-map'] = array("class"=>'outline', "tags"=>'map',"unicode"=>'e6b5');
$icons_set['outline']['outline-map-route'] = array("class"=>'outline', "tags"=>'map-route',"unicode"=>'e6b6');
$icons_set['outline']['outline-map-pins'] = array("class"=>'outline', "tags"=>'map-pins',"unicode"=>'e6b7');
$icons_set['outline']['outline-map-pin'] = array("class"=>'outline', "tags"=>'map-pin',"unicode"=>'e6b8');
$icons_set['outline']['outline-tv-cabinet'] = array("class"=>'outline', "tags"=>'tv-cabinet',"unicode"=>'e6b9');
$icons_set['outline']['outline-trophy'] = array("class"=>'outline', "tags"=>'trophy',"unicode"=>'e6ba');
$icons_set['outline']['outline-stool'] = array("class"=>'outline', "tags"=>'stool',"unicode"=>'e6bb');
$icons_set['outline']['outline-single-bed'] = array("class"=>'outline', "tags"=>'single-bed',"unicode"=>'e6bc');
$icons_set['outline']['outline-rugby-ball'] = array("class"=>'outline', "tags"=>'rugby-ball',"unicode"=>'e6bd');
$icons_set['outline']['outline-pint-glass'] = array("class"=>'outline', "tags"=>'pint-glass',"unicode"=>'e6be');
$icons_set['outline']['outline-office-chair'] = array("class"=>'outline', "tags"=>'office-chair',"unicode"=>'e6bf');
$icons_set['outline']['outline-network-link'] = array("class"=>'outline', "tags"=>'network-link',"unicode"=>'e6c0');
$icons_set['outline']['outline-network-open'] = array("class"=>'outline', "tags"=>'network-open',"unicode"=>'e6c1');
$icons_set['outline']['outline-stop'] = array("class"=>'outline', "tags"=>'stop',"unicode"=>'e6c2');
$icons_set['outline']['outline-sink'] = array("class"=>'outline', "tags"=>'sink',"unicode"=>'e6c3');
$icons_set['outline']['outline-ruler'] = array("class"=>'outline', "tags"=>'ruler',"unicode"=>'e6c4');
$icons_set['outline']['outline-pinwheel'] = array("class"=>'outline', "tags"=>'pinwheel',"unicode"=>'e6c5');
$icons_set['outline']['outline-opposite-horizontal-arrows'] = array("class"=>'outline', "tags"=>'opposite-horizontal-arrows',"unicode"=>'e6c6');
$icons_set['outline']['outline-yen-yuan'] = array("class"=>'outline', "tags"=>'yen-yuan',"unicode"=>'e6c7');
$icons_set['outline']['outline-map-pin-tick'] = array("class"=>'outline', "tags"=>'map-pin-tick',"unicode"=>'e6c8');
$icons_set['outline']['outline-map-pin-remove'] = array("class"=>'outline', "tags"=>'map-pin-remove',"unicode"=>'e6c9');
$icons_set['outline']['outline-map-pin-delete'] = array("class"=>'outline', "tags"=>'map-pin-delete',"unicode"=>'e6ca');
$icons_set['outline']['outline-map-pin-add'] = array("class"=>'outline', "tags"=>'map-pin-add',"unicode"=>'e6cb');
$icons_set['outline']['outline-map-path'] = array("class"=>'outline', "tags"=>'map-path',"unicode"=>'e6cc');
$icons_set['outline']['outline-map-location'] = array("class"=>'outline', "tags"=>'map-location',"unicode"=>'e6cd');
$icons_set['outline']['outline-man'] = array("class"=>'outline', "tags"=>'man',"unicode"=>'e6ce');
$icons_set['outline']['outline-male-symbol'] = array("class"=>'outline', "tags"=>'male-symbol',"unicode"=>'e6cf');
$icons_set['outline']['outline-male-female-symbol'] = array("class"=>'outline', "tags"=>'male-female-symbol',"unicode"=>'e6d0');
$icons_set['outline']['outline-luggage'] = array("class"=>'outline', "tags"=>'luggage',"unicode"=>'e6d1');
$icons_set['outline']['outline-loop'] = array("class"=>'outline', "tags"=>'loop',"unicode"=>'e6d2');
$icons_set['outline']['outline-lollipop'] = array("class"=>'outline', "tags"=>'lollipop',"unicode"=>'e6d3');
$icons_set['outline']['outline-kickboxing'] = array("class"=>'outline', "tags"=>'kickboxing',"unicode"=>'e6d4');
$icons_set['outline']['outline-keypad'] = array("class"=>'outline', "tags"=>'keypad',"unicode"=>'e6d5');
$icons_set['outline']['outline-karate'] = array("class"=>'outline', "tags"=>'karate',"unicode"=>'e6d6');
$icons_set['outline']['outline-jump-forward'] = array("class"=>'outline', "tags"=>'jump-forward',"unicode"=>'e6d7');
$icons_set['outline']['outline-jump-back'] = array("class"=>'outline', "tags"=>'jump-back',"unicode"=>'e6d8');
$icons_set['outline']['outline-joystick'] = array("class"=>'outline', "tags"=>'joystick',"unicode"=>'e6d9');
$icons_set['outline']['outline-jogging'] = array("class"=>'outline', "tags"=>'jogging',"unicode"=>'e6da');
$icons_set['outline']['outline-jigsaw'] = array("class"=>'outline', "tags"=>'jigsaw',"unicode"=>'e6db');
$icons_set['outline']['outline-jewel'] = array("class"=>'outline', "tags"=>'jewel',"unicode"=>'e6dc');
$icons_set['outline']['outline-interfaces'] = array("class"=>'outline', "tags"=>'interfaces',"unicode"=>'e6dd');
$icons_set['outline']['outline-interface-two-panel'] = array("class"=>'outline', "tags"=>'interface-two-panel',"unicode"=>'e6de');
$icons_set['outline']['outline-interface-three-panel'] = array("class"=>'outline', "tags"=>'interface-three-panel',"unicode"=>'e6df');
$icons_set['outline']['outline-headphones'] = array("class"=>'outline', "tags"=>'headphones',"unicode"=>'e6e0');
$icons_set['outline']['outline-happy-face'] = array("class"=>'outline', "tags"=>'happy-face',"unicode"=>'e6e1');
$icons_set['outline']['outline-hamburger'] = array("class"=>'outline', "tags"=>'hamburger',"unicode"=>'e6e2');
$icons_set['outline']['outline-gymnastics'] = array("class"=>'outline', "tags"=>'gymnastics',"unicode"=>'e6e3');
$icons_set['outline']['outline-group'] = array("class"=>'outline', "tags"=>'group',"unicode"=>'e6e4');
$icons_set['outline']['outline-group-tick'] = array("class"=>'outline', "tags"=>'group-tick',"unicode"=>'e6e5');
$icons_set['outline']['outline-group-remove'] = array("class"=>'outline', "tags"=>'group-remove',"unicode"=>'e6e6');
$icons_set['outline']['outline-group-delete'] = array("class"=>'outline', "tags"=>'group-delete',"unicode"=>'e6e7');
$icons_set['outline']['outline-group-add'] = array("class"=>'outline', "tags"=>'group-add',"unicode"=>'e6e8');
$icons_set['outline']['outline-golf-swing'] = array("class"=>'outline', "tags"=>'golf-swing',"unicode"=>'e6e9');
$icons_set['outline']['outline-golf-putting'] = array("class"=>'outline', "tags"=>'golf-putting',"unicode"=>'e6ea');
$icons_set['outline']['outline-globe'] = array("class"=>'outline', "tags"=>'globe',"unicode"=>'e6eb');
$icons_set['outline']['outline-flag-rectangle'] = array("class"=>'outline', "tags"=>'flag-rectangle',"unicode"=>'e6ec');
$icons_set['outline']['outline-flag-fanion'] = array("class"=>'outline', "tags"=>'flag-fanion',"unicode"=>'e6ed');
$icons_set['outline']['outline-fingerprint'] = array("class"=>'outline', "tags"=>'fingerprint',"unicode"=>'e6ee');
$icons_set['outline']['outline-filter'] = array("class"=>'outline', "tags"=>'filter',"unicode"=>'e6ef');
$icons_set['outline']['outline-films'] = array("class"=>'outline', "tags"=>'films',"unicode"=>'e6f0');
$icons_set['outline']['outline-filing-triple'] = array("class"=>'outline', "tags"=>'filing-triple',"unicode"=>'e6f1');
$icons_set['outline']['outline-filing-double'] = array("class"=>'outline', "tags"=>'filing-double',"unicode"=>'e6f2');
$icons_set['outline']['outline-files'] = array("class"=>'outline', "tags"=>'files',"unicode"=>'e6f3');
$icons_set['outline']['outline-file'] = array("class"=>'outline', "tags"=>'file',"unicode"=>'e6f4');
$icons_set['outline']['outline-file-zip'] = array("class"=>'outline', "tags"=>'file-zip',"unicode"=>'e6f5');
$icons_set['outline']['outline-file-xml'] = array("class"=>'outline', "tags"=>'file-xml',"unicode"=>'e6f6');
$icons_set['outline']['outline-file-xls'] = array("class"=>'outline', "tags"=>'file-xls',"unicode"=>'e6f7');
$icons_set['outline']['outline-file-report'] = array("class"=>'outline', "tags"=>'file-report',"unicode"=>'e6f8');
$icons_set['outline']['outline-file-recording'] = array("class"=>'outline', "tags"=>'file-recording',"unicode"=>'e6f9');
$icons_set['outline']['outline-file-raw'] = array("class"=>'outline', "tags"=>'file-raw',"unicode"=>'e6fa');
$icons_set['outline']['outline-file-rar'] = array("class"=>'outline', "tags"=>'file-rar',"unicode"=>'e6fb');
$icons_set['outline']['outline-file-psd'] = array("class"=>'outline', "tags"=>'file-psd',"unicode"=>'e6fc');
$icons_set['outline']['outline-file-ps'] = array("class"=>'outline', "tags"=>'file-ps',"unicode"=>'e6fd');
$icons_set['outline']['outline-file-protection'] = array("class"=>'outline', "tags"=>'file-protection',"unicode"=>'e6fe');
$icons_set['outline']['outline-file-profile'] = array("class"=>'outline', "tags"=>'file-profile',"unicode"=>'e6ff');
$icons_set['outline']['outline-file-presentation'] = array("class"=>'outline', "tags"=>'file-presentation',"unicode"=>'e700');
$icons_set['outline']['outline-file-ppt'] = array("class"=>'outline', "tags"=>'file-ppt',"unicode"=>'e701');
$icons_set['outline']['outline-file-png'] = array("class"=>'outline', "tags"=>'file-png',"unicode"=>'e702');
$icons_set['outline']['outline-file-plans'] = array("class"=>'outline', "tags"=>'file-plans',"unicode"=>'e703');
$icons_set['outline']['outline-file-html'] = array("class"=>'outline', "tags"=>'file-html',"unicode"=>'e704');
$icons_set['outline']['outline-file-graph'] = array("class"=>'outline', "tags"=>'file-graph',"unicode"=>'e705');
$icons_set['outline']['outline-file-gif'] = array("class"=>'outline', "tags"=>'file-gif',"unicode"=>'e706');
$icons_set['outline']['outline-file-font'] = array("class"=>'outline', "tags"=>'file-font',"unicode"=>'e707');
$icons_set['outline']['outline-file-flv'] = array("class"=>'outline', "tags"=>'file-flv',"unicode"=>'e708');
$icons_set['outline']['outline-file-favourite'] = array("class"=>'outline', "tags"=>'file-favourite',"unicode"=>'e709');
$icons_set['outline']['outline-file-exe'] = array("class"=>'outline', "tags"=>'file-exe',"unicode"=>'e70a');
$icons_set['outline']['outline-file-eps'] = array("class"=>'outline', "tags"=>'file-eps',"unicode"=>'e70b');
$icons_set['outline']['outline-file-edit'] = array("class"=>'outline', "tags"=>'file-edit',"unicode"=>'e70c');
$icons_set['outline']['outline-file-doc'] = array("class"=>'outline', "tags"=>'file-doc',"unicode"=>'e70d');
$icons_set['outline']['outline-file-dll'] = array("class"=>'outline', "tags"=>'file-dll',"unicode"=>'e70e');
$icons_set['outline']['outline-file-db'] = array("class"=>'outline', "tags"=>'file-db',"unicode"=>'e70f');
$icons_set['outline']['outline-favorites'] = array("class"=>'outline', "tags"=>'favorites',"unicode"=>'e710');
$icons_set['outline']['outline-exclamation'] = array("class"=>'outline', "tags"=>'exclamation',"unicode"=>'e711');
$icons_set['outline']['outline-euro'] = array("class"=>'outline', "tags"=>'euro',"unicode"=>'e712');
$icons_set['outline']['outline-equals'] = array("class"=>'outline', "tags"=>'equals',"unicode"=>'e713');
$icons_set['outline']['outline-end'] = array("class"=>'outline', "tags"=>'end',"unicode"=>'e714');
$icons_set['outline']['outline-email'] = array("class"=>'outline', "tags"=>'email',"unicode"=>'e715');
$icons_set['outline']['outline-electronic-megaphone'] = array("class"=>'outline', "tags"=>'electronic-megaphone',"unicode"=>'e716');
$icons_set['outline']['outline-eject'] = array("class"=>'outline', "tags"=>'eject',"unicode"=>'e717');
$icons_set['outline']['outline-dress'] = array("class"=>'outline', "tags"=>'dress',"unicode"=>'e718');
$icons_set['outline']['outline-download'] = array("class"=>'outline', "tags"=>'download',"unicode"=>'e719');
$icons_set['outline']['outline-double-bed'] = array("class"=>'outline', "tags"=>'double-bed',"unicode"=>'e71a');
$icons_set['outline']['outline-dollar'] = array("class"=>'outline', "tags"=>'dollar',"unicode"=>'e71b');
$icons_set['outline']['outline-database-delete'] = array("class"=>'outline', "tags"=>'database-delete',"unicode"=>'e71c');
$icons_set['outline']['outline-database-add'] = array("class"=>'outline', "tags"=>'database-add',"unicode"=>'e71d');
$icons_set['outline']['outline-cycling'] = array("class"=>'outline', "tags"=>'cycling',"unicode"=>'e71e');
$icons_set['outline']['outline-cutlery'] = array("class"=>'outline', "tags"=>'cutlery',"unicode"=>'e71f');
$icons_set['outline']['outline-curly-brackets'] = array("class"=>'outline', "tags"=>'curly-brackets',"unicode"=>'e720');
$icons_set['outline']['outline-cube'] = array("class"=>'outline', "tags"=>'cube',"unicode"=>'e721');
$icons_set['outline']['outline-cross-country-skiing'] = array("class"=>'outline', "tags"=>'cross-country-skiing',"unicode"=>'e722');
$icons_set['outline']['outline-contact'] = array("class"=>'outline', "tags"=>'contact',"unicode"=>'e723');
$icons_set['outline']['outline-computer'] = array("class"=>'outline', "tags"=>'computer',"unicode"=>'e724');
$icons_set['outline']['outline-computer-desk'] = array("class"=>'outline', "tags"=>'computer-desk',"unicode"=>'e725');
$icons_set['outline']['outline-compass'] = array("class"=>'outline', "tags"=>'compass',"unicode"=>'e726');
$icons_set['outline']['outline-combination-lock-open'] = array("class"=>'outline', "tags"=>'combination-lock-open',"unicode"=>'e727');
$icons_set['outline']['outline-clipboard'] = array("class"=>'outline', "tags"=>'clipboard',"unicode"=>'e728');
$icons_set['outline']['outline-chupa-chups'] = array("class"=>'outline', "tags"=>'chupa-chups',"unicode"=>'e729');
$icons_set['outline']['outline-cheeseburger'] = array("class"=>'outline', "tags"=>'cheeseburger',"unicode"=>'e72a');
$icons_set['outline']['outline-checkbox'] = array("class"=>'outline', "tags"=>'checkbox',"unicode"=>'e72b');
$icons_set['outline']['outline-chats'] = array("class"=>'outline', "tags"=>'chats',"unicode"=>'e72c');
$icons_set['outline']['outline-chat'] = array("class"=>'outline', "tags"=>'chat',"unicode"=>'e72d');
$icons_set['outline']['outline-chat-reply'] = array("class"=>'outline', "tags"=>'chat-reply',"unicode"=>'e72e');
$icons_set['outline']['outline-chart-up'] = array("class"=>'outline', "tags"=>'chart-up',"unicode"=>'e72f');
$icons_set['outline']['outline-chart-down'] = array("class"=>'outline', "tags"=>'chart-down',"unicode"=>'e730');
$icons_set['outline']['outline-char-z'] = array("class"=>'outline', "tags"=>'char-z',"unicode"=>'e731');
$icons_set['outline']['outline-char-y'] = array("class"=>'outline', "tags"=>'char-y',"unicode"=>'e732');
$icons_set['outline']['outline-char-x'] = array("class"=>'outline', "tags"=>'char-x',"unicode"=>'e733');
$icons_set['outline']['outline-char-j'] = array("class"=>'outline', "tags"=>'char-j',"unicode"=>'e734');
$icons_set['outline']['outline-char-i'] = array("class"=>'outline', "tags"=>'char-i',"unicode"=>'e735');
$icons_set['outline']['outline-char-h'] = array("class"=>'outline', "tags"=>'char-h',"unicode"=>'e736');
$icons_set['outline']['outline-char-g'] = array("class"=>'outline', "tags"=>'char-g',"unicode"=>'e737');
$icons_set['outline']['outline-char-f'] = array("class"=>'outline', "tags"=>'char-f',"unicode"=>'e738');
$icons_set['outline']['outline-char-e'] = array("class"=>'outline', "tags"=>'char-e',"unicode"=>'e739');
$icons_set['outline']['outline-char-d'] = array("class"=>'outline', "tags"=>'char-d',"unicode"=>'e73a');
$icons_set['outline']['outline-char-c'] = array("class"=>'outline', "tags"=>'char-c',"unicode"=>'e73b');
$icons_set['outline']['outline-char-b'] = array("class"=>'outline', "tags"=>'char-b',"unicode"=>'e73c');
$icons_set['outline']['outline-char-a'] = array("class"=>'outline', "tags"=>'char-a',"unicode"=>'e73d');
$icons_set['outline']['outline-chair'] = array("class"=>'outline', "tags"=>'chair',"unicode"=>'e73e');
$icons_set['outline']['outline-bookmarks'] = array("class"=>'outline', "tags"=>'bookmarks',"unicode"=>'e740');
$icons_set['outline']['outline-book'] = array("class"=>'outline', "tags"=>'book',"unicode"=>'e741');
$icons_set['outline']['outline-bluetooth'] = array("class"=>'outline', "tags"=>'bluetooth',"unicode"=>'e742');
$icons_set['outline']['outline-bell'] = array("class"=>'outline', "tags"=>'bell',"unicode"=>'e743');
$icons_set['outline']['outline-bathroom-cabinet'] = array("class"=>'outline', "tags"=>'bathroom-cabinet',"unicode"=>'e744');
$icons_set['outline']['outline-bath-shower'] = array("class"=>'outline', "tags"=>'bath-shower',"unicode"=>'e745');
$icons_set['outline']['outline-basketball'] = array("class"=>'outline', "tags"=>'basketball',"unicode"=>'e746');
$icons_set['outline']['outline-basketball-player'] = array("class"=>'outline', "tags"=>'basketball-player',"unicode"=>'e747');
$icons_set['outline']['outline-baseball'] = array("class"=>'outline', "tags"=>'baseball',"unicode"=>'e748');
$icons_set['outline']['outline-baseball-player'] = array("class"=>'outline', "tags"=>'baseball-player',"unicode"=>'e749');
$icons_set['outline']['outline-bar-chart'] = array("class"=>'outline', "tags"=>'bar-chart',"unicode"=>'e74a');
$icons_set['outline']['outline-bar_stool'] = array("class"=>'outline', "tags"=>'bar-stool',"unicode"=>'e74b');
$icons_set['outline']['outline-american-footballer'] = array("class"=>'outline', "tags"=>'american-footballer',"unicode"=>'e74c');
$icons_set['outline']['outline-albums'] = array("class"=>'outline', "tags"=>'albums',"unicode"=>'e74d');
$icons_set['outline']['outline-alarm'] = array("class"=>'outline', "tags"=>'alarm',"unicode"=>'e74e');
$icons_set['outline']['outline-airdrop'] = array("class"=>'outline', "tags"=>'airdrop',"unicode"=>'e74f');
$icons_set['outline']['outline-aim-target'] = array("class"=>'outline', "tags"=>'aim-target',"unicode"=>'e750');
$icons_set['outline']['outline-pin-bowling'] = array("class"=>'outline', "tags"=>'pin-bowling',"unicode"=>'e751');
$icons_set['outline']['outline-location'] = array("class"=>'outline', "tags"=>'location',"unicode"=>'e752');
$icons_set['outline']['outline-list'] = array("class"=>'outline', "tags"=>'list',"unicode"=>'e753');
$icons_set['outline']['outline-lightening'] = array("class"=>'outline', "tags"=>'lightening',"unicode"=>'e754');
$icons_set['outline']['outline-light'] = array("class"=>'outline', "tags"=>'light',"unicode"=>'e755');
$icons_set['outline']['outline-light-bulb'] = array("class"=>'outline', "tags"=>'light-bulb',"unicode"=>'e756');
$icons_set['outline']['outline-light-bulb-on'] = array("class"=>'outline', "tags"=>'light-bulb-on',"unicode"=>'e757');
$icons_set['outline']['outline-lifebelt'] = array("class"=>'outline', "tags"=>'lifebelt',"unicode"=>'e758');
$icons_set['outline']['outline-less-than'] = array("class"=>'outline', "tags"=>'less-than',"unicode"=>'e759');
$icons_set['outline']['outline-less-than-or-equal'] = array("class"=>'outline', "tags"=>'less-than-or-equal',"unicode"=>'e75a');
$icons_set['outline']['outline-ledger'] = array("class"=>'outline', "tags"=>'ledger',"unicode"=>'e75b');
$icons_set['outline']['outline-layers'] = array("class"=>'outline', "tags"=>'layers',"unicode"=>'e75c');
$icons_set['outline']['outline-laptop'] = array("class"=>'outline', "tags"=>'laptop',"unicode"=>'e75d');
$icons_set['outline']['outline-lamp'] = array("class"=>'outline', "tags"=>'lamp',"unicode"=>'e75e');
$icons_set['outline']['outline-interface-side-by-side'] = array("class"=>'outline', "tags"=>'interface-side-by-side',"unicode"=>'e75f');
$icons_set['outline']['outline-interface-one-panel'] = array("class"=>'outline', "tags"=>'interface-one-panel',"unicode"=>'e760');
$icons_set['outline']['outline-info'] = array("class"=>'outline', "tags"=>'info',"unicode"=>'e761');
$icons_set['outline']['outline-id'] = array("class"=>'outline', "tags"=>'id',"unicode"=>'e762');
$icons_set['outline']['outline-ice-lolly'] = array("class"=>'outline', "tags"=>'ice-lolly',"unicode"=>'e763');
$icons_set['outline']['outline-ice-hockey'] = array("class"=>'outline', "tags"=>'ice-hockey',"unicode"=>'e764');
$icons_set['outline']['outline-ice-cream'] = array("class"=>'outline', "tags"=>'ice-cream',"unicode"=>'e765');
$icons_set['outline']['outline-hurdles'] = array("class"=>'outline', "tags"=>'hurdles',"unicode"=>'e766');
$icons_set['outline']['outline-horizontal-slider'] = array("class"=>'outline', "tags"=>'horizontal-slider',"unicode"=>'e767');
$icons_set['outline']['outline-home'] = array("class"=>'outline', "tags"=>'home',"unicode"=>'e768');
$icons_set['outline']['outline-hockey'] = array("class"=>'outline', "tags"=>'hockey',"unicode"=>'e769');
$icons_set['outline']['outline-heart'] = array("class"=>'outline', "tags"=>'heart',"unicode"=>'e76a');
$icons_set['outline']['outline-headset'] = array("class"=>'outline', "tags"=>'headset',"unicode"=>'e76b');
$icons_set['outline']['outline-games-ios'] = array("class"=>'outline', "tags"=>'games-ios',"unicode"=>'e76c');
$icons_set['outline']['outline-forward'] = array("class"=>'outline', "tags"=>'forward',"unicode"=>'e76d');
$icons_set['outline']['outline-forward-arrow'] = array("class"=>'outline', "tags"=>'forward-arrow',"unicode"=>'e76e');
$icons_set['outline']['outline-football'] = array("class"=>'outline', "tags"=>'football',"unicode"=>'e76f');
$icons_set['outline']['outline-folders'] = array("class"=>'outline', "tags"=>'folders',"unicode"=>'e770');
$icons_set['outline']['outline-folder'] = array("class"=>'outline', "tags"=>'folder',"unicode"=>'e771');
$icons_set['outline']['outline-folder-tick'] = array("class"=>'outline', "tags"=>'folder-tick',"unicode"=>'e772');
$icons_set['outline']['outline-folder-remove'] = array("class"=>'outline', "tags"=>'folder-remove',"unicode"=>'e773');
$icons_set['outline']['outline-folder-delete'] = array("class"=>'outline', "tags"=>'folder-delete',"unicode"=>'e774');
$icons_set['outline']['outline-folder-add'] = array("class"=>'outline', "tags"=>'folder-add',"unicode"=>'e775');
$icons_set['outline']['outline-floor-lamp'] = array("class"=>'outline', "tags"=>'floor-lamp',"unicode"=>'e776');
$icons_set['outline']['outline-flag'] = array("class"=>'outline', "tags"=>'flag',"unicode"=>'e777');
$icons_set['outline']['outline-flag-swallow'] = array("class"=>'outline', "tags"=>'flag-swallow',"unicode"=>'e778');
$icons_set['outline']['outline-file-woff'] = array("class"=>'outline', "tags"=>'file-woff',"unicode"=>'e779');
$icons_set['outline']['outline-file-wmv'] = array("class"=>'outline', "tags"=>'file-wmv',"unicode"=>'e77a');
$icons_set['outline']['outline-file-wma'] = array("class"=>'outline', "tags"=>'file-wma',"unicode"=>'e77b');
$icons_set['outline']['outline-file-wav'] = array("class"=>'outline', "tags"=>'file-wav',"unicode"=>'e77c');
$icons_set['outline']['outline-file-video'] = array("class"=>'outline', "tags"=>'file-video',"unicode"=>'e77d');
$icons_set['outline']['outline-file-txt'] = array("class"=>'outline', "tags"=>'file-txt',"unicode"=>'e77e');
$icons_set['outline']['outline-file-ttf'] = array("class"=>'outline', "tags"=>'file-ttf',"unicode"=>'e77f');
$icons_set['outline']['outline-file-tif'] = array("class"=>'outline', "tags"=>'file-tif',"unicode"=>'e780');
$icons_set['outline']['outline-file-tar'] = array("class"=>'outline', "tags"=>'file-tar',"unicode"=>'e781');
$icons_set['outline']['outline-file-svg'] = array("class"=>'outline', "tags"=>'file-svg',"unicode"=>'e782');
$icons_set['outline']['outline-file-sql'] = array("class"=>'outline', "tags"=>'file-sql',"unicode"=>'e783');
$icons_set['outline']['outline-file-spreadsheet'] = array("class"=>'outline', "tags"=>'file-spreadsheet',"unicode"=>'e784');
$icons_set['outline']['outline-file-setting'] = array("class"=>'outline', "tags"=>'file-setting',"unicode"=>'e785');
$icons_set['outline']['outline-file-picture'] = array("class"=>'outline', "tags"=>'file-picture',"unicode"=>'e786');
$icons_set['outline']['outline-file-pdf'] = array("class"=>'outline', "tags"=>'file-pdf',"unicode"=>'e787');
$icons_set['outline']['outline-file-pct'] = array("class"=>'outline', "tags"=>'file-pct',"unicode"=>'e788');
$icons_set['outline']['outline-file-page'] = array("class"=>'outline', "tags"=>'file-page',"unicode"=>'e789');
$icons_set['outline']['outline-file-otf'] = array("class"=>'outline', "tags"=>'file-otf',"unicode"=>'e78a');
$icons_set['outline']['outline-file-mpg'] = array("class"=>'outline', "tags"=>'file-mpg',"unicode"=>'e78b');
$icons_set['outline']['outline-file-mp4'] = array("class"=>'outline', "tags"=>'file-mp4',"unicode"=>'e78c');
$icons_set['outline']['outline-file-mp3'] = array("class"=>'outline', "tags"=>'file-mp3',"unicode"=>'e78d');
$icons_set['outline']['outline-file-mov'] = array("class"=>'outline', "tags"=>'file-mov',"unicode"=>'e78e');
$icons_set['outline']['outline-file-locked'] = array("class"=>'outline', "tags"=>'file-locked',"unicode"=>'e78f');
$icons_set['outline']['outline-file-liked'] = array("class"=>'outline', "tags"=>'file-liked',"unicode"=>'e790');
$icons_set['outline']['outline-file-key'] = array("class"=>'outline', "tags"=>'file-key',"unicode"=>'e791');
$icons_set['outline']['outline-file-jpg'] = array("class"=>'outline', "tags"=>'file-jpg',"unicode"=>'e792');
$icons_set['outline']['outline-file-csv'] = array("class"=>'outline', "tags"=>'file-csv',"unicode"=>'e793');
$icons_set['outline']['outline-file-css'] = array("class"=>'outline', "tags"=>'file-css',"unicode"=>'e794');
$icons_set['outline']['outline-file-compression'] = array("class"=>'outline', "tags"=>'file-compression',"unicode"=>'e795');
$icons_set['outline']['outline-file-code'] = array("class"=>'outline', "tags"=>'file-code',"unicode"=>'e796');
$icons_set['outline']['outline-file-bmp'] = array("class"=>'outline', "tags"=>'file-bmp',"unicode"=>'e797');
$icons_set['outline']['outline-file-avi'] = array("class"=>'outline', "tags"=>'file-avi',"unicode"=>'e798');
$icons_set['outline']['outline-file-audio'] = array("class"=>'outline', "tags"=>'file-audio',"unicode"=>'e799');
$icons_set['outline']['outline-file-aiff'] = array("class"=>'outline', "tags"=>'file-aiff',"unicode"=>'e79a');
$icons_set['outline']['outline-file-ai'] = array("class"=>'outline', "tags"=>'file-ai',"unicode"=>'e79b');
$icons_set['outline']['outline-file-aac'] = array("class"=>'outline', "tags"=>'file-aac',"unicode"=>'e79c');
$icons_set['outline']['outline-figure-skating'] = array("class"=>'outline', "tags"=>'figure-skating',"unicode"=>'e79d');
$icons_set['outline']['outline-fencing'] = array("class"=>'outline', "tags"=>'fencing',"unicode"=>'e79e');
$icons_set['outline']['outline-female-symbol'] = array("class"=>'outline', "tags"=>'female-symbol',"unicode"=>'e79f');
$icons_set['outline']['outline-documents'] = array("class"=>'outline', "tags"=>'documents',"unicode"=>'e7a0');
$icons_set['outline']['outline-document'] = array("class"=>'outline', "tags"=>'document',"unicode"=>'e7a1');
$icons_set['outline']['outline-document-tick'] = array("class"=>'outline', "tags"=>'document-tick',"unicode"=>'e7a2');
$icons_set['outline']['outline-document-remove'] = array("class"=>'outline', "tags"=>'document-remove',"unicode"=>'e7a3');
$icons_set['outline']['outline-document-delete'] = array("class"=>'outline', "tags"=>'document-delete',"unicode"=>'e7a4');
$icons_set['outline']['outline-document-add'] = array("class"=>'outline', "tags"=>'document-add',"unicode"=>'e7a5');
$icons_set['outline']['outline-divider'] = array("class"=>'outline', "tags"=>'divider',"unicode"=>'e7a6');
$icons_set['outline']['outline-divide'] = array("class"=>'outline', "tags"=>'divide',"unicode"=>'e7a7');
$icons_set['outline']['outline-divide-slash'] = array("class"=>'outline', "tags"=>'divide-slash',"unicode"=>'e7a8');
$icons_set['outline']['outline-dining-chair'] = array("class"=>'outline', "tags"=>'dining-chair',"unicode"=>'e7a9');
$icons_set['outline']['outline-desk-lamp'] = array("class"=>'outline', "tags"=>'desk-lamp',"unicode"=>'e7aa');
$icons_set['outline']['outline-dawers'] = array("class"=>'outline', "tags"=>'dawers',"unicode"=>'e7ab');
$icons_set['outline']['outline-database'] = array("class"=>'outline', "tags"=>'database',"unicode"=>'e7ac');
$icons_set['outline']['outline-combination-lock-closed'] = array("class"=>'outline', "tags"=>'combination-lock-closed',"unicode"=>'e7ad');
$icons_set['outline']['outline-coins-yen-yuan'] = array("class"=>'outline', "tags"=>'coins-yen-yuan',"unicode"=>'e7ae');
$icons_set['outline']['outline-coins-rupee'] = array("class"=>'outline', "tags"=>'coins-rupee',"unicode"=>'e7af');
$icons_set['outline']['outline-coins-pound'] = array("class"=>'outline', "tags"=>'coins-pound',"unicode"=>'e7b0');
$icons_set['outline']['outline-coins-euro'] = array("class"=>'outline', "tags"=>'coins-euro',"unicode"=>'e7b1');
$icons_set['outline']['outline-coins-dollar'] = array("class"=>'outline', "tags"=>'coins-dollar',"unicode"=>'e7b2');
$icons_set['outline']['outline-cog'] = array("class"=>'outline', "tags"=>'cog',"unicode"=>'e7b3');
$icons_set['outline']['outline-coffee-cup'] = array("class"=>'outline', "tags"=>'coffee-cup',"unicode"=>'e7b4');
$icons_set['outline']['outline-coat-hanger'] = array("class"=>'outline', "tags"=>'coat-hanger',"unicode"=>'e7b5');
$icons_set['outline']['outline-cloud-upload'] = array("class"=>'outline', "tags"=>'cloud-upload',"unicode"=>'e7b6');
$icons_set['outline']['outline-cloud-remove'] = array("class"=>'outline', "tags"=>'cloud-remove',"unicode"=>'e7b7');
$icons_set['outline']['outline-cloud-download'] = array("class"=>'outline', "tags"=>'cloud-download',"unicode"=>'e7b8');
$icons_set['outline']['outline-cloud-add'] = array("class"=>'outline', "tags"=>'cloud-add',"unicode"=>'e7b9');
$icons_set['outline']['outline-char-w'] = array("class"=>'outline', "tags"=>'char-w',"unicode"=>'e7ba');
$icons_set['outline']['outline-char-v'] = array("class"=>'outline', "tags"=>'char-v',"unicode"=>'e7bb');
$icons_set['outline']['outline-char-u'] = array("class"=>'outline', "tags"=>'char-u',"unicode"=>'e7bc');
$icons_set['outline']['outline-char-t'] = array("class"=>'outline', "tags"=>'char-t',"unicode"=>'e7bd');
$icons_set['outline']['outline-char-s'] = array("class"=>'outline', "tags"=>'char-s',"unicode"=>'e7be');
$icons_set['outline']['outline-char-r'] = array("class"=>'outline', "tags"=>'char-r',"unicode"=>'e7bf');
$icons_set['outline']['outline-char-q'] = array("class"=>'outline', "tags"=>'char-q',"unicode"=>'e7c0');
$icons_set['outline']['outline-char-p'] = array("class"=>'outline', "tags"=>'char-p',"unicode"=>'e7c1');
$icons_set['outline']['outline-char-o'] = array("class"=>'outline', "tags"=>'char-o',"unicode"=>'e7c2');
$icons_set['outline']['outline-char-n'] = array("class"=>'outline', "tags"=>'char-n',"unicode"=>'e7c3');
$icons_set['outline']['outline-char-m'] = array("class"=>'outline', "tags"=>'char-m',"unicode"=>'e7c4');
$icons_set['outline']['outline-char-l'] = array("class"=>'outline', "tags"=>'char-l',"unicode"=>'e7c5');
$icons_set['outline']['outline-char-k'] = array("class"=>'outline', "tags"=>'char-k',"unicode"=>'e7c6');
$icons_set['outline']['outline-camera'] = array("class"=>'outline', "tags"=>'camera',"unicode"=>'e7c7');
$icons_set['outline']['outline-camera-rotate'] = array("class"=>'outline', "tags"=>'camera-rotate',"unicode"=>'e7c8');
$icons_set['outline']['outline-calendar'] = array("class"=>'outline', "tags"=>'calendar',"unicode"=>'e7c9');
$icons_set['outline']['outline-calculator'] = array("class"=>'outline', "tags"=>'calculator',"unicode"=>'e7ca');
$icons_set['outline']['outline-bunk-bed'] = array("class"=>'outline', "tags"=>'bunk-bed',"unicode"=>'e7cb');
$icons_set['outline']['outline-browsers'] = array("class"=>'outline', "tags"=>'browsers',"unicode"=>'e7cc');
$icons_set['outline']['outline-broken-heart'] = array("class"=>'outline', "tags"=>'broken-heart',"unicode"=>'e7cd');
$icons_set['outline']['outline-briefcase'] = array("class"=>'outline', "tags"=>'briefcase',"unicode"=>'e7ce');
$icons_set['outline']['outline-brackets'] = array("class"=>'outline', "tags"=>'brackets',"unicode"=>'e7cf');
$icons_set['outline']['outline-box-open'] = array("class"=>'outline', "tags"=>'box-open',"unicode"=>'e7d0');
$icons_set['outline']['outline-box-closed'] = array("class"=>'outline', "tags"=>'box-closed',"unicode"=>'e7d1');
$icons_set['outline']['outline-bowling-ball'] = array("class"=>'outline', "tags"=>'bowling-ball',"unicode"=>'e7d2');
$icons_set['outline']['outline-bottle-glass'] = array("class"=>'outline', "tags"=>'bottle-glass',"unicode"=>'e7d3');
$icons_set['outline']['outline-at'] = array("class"=>'outline', "tags"=>'at',"unicode"=>'e7d4');
$icons_set['outline']['outline-asterisk'] = array("class"=>'outline', "tags"=>'asterisk',"unicode"=>'e7d5');
$icons_set['outline']['outline-arrows-out'] = array("class"=>'outline', "tags"=>'arrows-out',"unicode"=>'e7d6');
$icons_set['outline']['outline-arrows-out-position'] = array("class"=>'outline', "tags"=>'arrows-out-position',"unicode"=>'e7d7');
$icons_set['outline']['outline-arrows-in'] = array("class"=>'outline', "tags"=>'arrows-in',"unicode"=>'e7d8');
$icons_set['outline']['outline-arrows-in-position'] = array("class"=>'outline', "tags"=>'arrows-in-position',"unicode"=>'e7d9');
$icons_set['outline']['outline-arrows-cross'] = array("class"=>'outline', "tags"=>'arrows-cross',"unicode"=>'e7da');
$icons_set['outline']['outline-armchair'] = array("class"=>'outline', "tags"=>'armchair',"unicode"=>'e7db');
$icons_set['outline']['outline-archery'] = array("class"=>'outline', "tags"=>'archery',"unicode"=>'e7dc');
$icons_set['outline']['outline-archery-target'] = array("class"=>'outline', "tags"=>'archery-target',"unicode"=>'e7dd');
$icons_set['outline']['outline-approximately'] = array("class"=>'outline', "tags"=>'approximately',"unicode"=>'e7de');
$icons_set['outline']['outline-anchor'] = array("class"=>'outline', "tags"=>'anchor',"unicode"=>'e7df');
$icons_set['outline']['outline-ampersand'] = array("class"=>'outline', "tags"=>'ampersand',"unicode"=>'e7e0');
?>