<?php
/*
* Config file with each demo data
*/

return array(
	'international'	=>	array(
		'demoName'				=>	'International',
		'liveURL'				=>	'http://www.highgradelab.com/sage/international/',
		'demoImg'				=>	'international.jpg',
		'xmlContentFile'		=>	'international.xml',
		'themeOptionsFile'		=>	'international.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	array('news-gallery.zip', 'sage-recipes.zip'),
	),
	'winery'			=>	array(
		'demoName'				=>	'Winery',
		'liveURL'				=>	'http://www.highgradelab.com/sage/winery/',
		'demoImg'				=>	'winery.jpg',
		'xmlContentFile'		=>	'winery.xml',
		'themeOptionsFile'		=>	'winery.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'seafood'		=>	array(
		'demoName'				=>	'Seafood',
		'liveURL'				=>	'http://www.highgradelab.com/sage/seafood/',
		'demoImg'				=>	'seafood.jpg',
		'xmlContentFile'		=>	'seafood.xml',
		'themeOptionsFile'		=>	'seafood.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	array('seafood.zip'),
	),
	'bakery'			=>	array(
		'demoName'				=>	'Bakery',
		'liveURL'				=>	'http://www.highgradelab.com/sage/bakery/',
		'demoImg'				=>	'bakery.jpg',
		'xmlContentFile'		=>	'bakery.xml',
		'themeOptionsFile'		=>	'bakery.json',
		'essentialGridFile'		=>	'bakery.json',
		'revSliderZipFiles'		=>	array('bakery.zip', 'bakery-recipes.zip'),
	),
	'catering'		=>	array(
		'demoName'				=>	'Catering',
		'liveURL'				=>	'http://www.highgradelab.com/sage/catering/',
		'demoImg'				=>	'catering.jpg',
		'xmlContentFile'		=>	'catering.xml',
		'themeOptionsFile'		=>	'catering.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	array('gallery.zip', 'catering.zip'),
	),
	'thai'			=>	array(
		'demoName'				=>	'Thai',
		'liveURL'				=>	'http://www.highgradelab.com/sage/thai/',
		'demoImg'				=>	'thai.jpg',
		'xmlContentFile'		=>	'thai.xml',
		'themeOptionsFile'		=>	'thai.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'steakhouse'		=>	array(
		'demoName'				=>	'Steak House',
		'liveURL'				=>	'http://www.highgradelab.com/sage/steak-house/',
		'demoImg'				=>	'steak-house.jpg',
		'xmlContentFile'		=>	'steakhouse.xml',
		'themeOptionsFile'		=>	'steakhouse.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'italian'		=>	array(
		'demoName'				=>	'Italian',
		'liveURL'				=>	'http://www.highgradelab.com/sage/italian/',
		'demoImg'				=>	'italian.jpg',
		'xmlContentFile'		=>	'italian.xml',
		'themeOptionsFile'		=>	'italian.json',
		'essentialGridFile'		=>	'organic.json',
		'revSliderZipFiles'		=>	false,
	),
	'organic'		=>	array(
		'demoName'				=>	'Organic',
		'liveURL'				=>	'http://www.highgradelab.com/sage/organic/',
		'demoImg'				=>	'organic.jpg',
		'xmlContentFile'		=>	'organic.xml',
		'themeOptionsFile'		=>	'organic.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'mexican'		=>	array(
		'demoName'				=>	'Mexican',
		'liveURL'				=>	'http://www.highgradelab.com/sage/mexican/',
		'demoImg'				=>	'mexican.jpg',
		'xmlContentFile'		=>	'mexican.xml',
		'themeOptionsFile'		=>	'mexican.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'french'			=>	array(
		'demoName'				=>	'French',
		'liveURL'				=>	'http://www.highgradelab.com/sage/french/',
		'demoImg'				=>	'french.jpg',
		'xmlContentFile'		=>	'french.xml',
		'themeOptionsFile'		=>	'french.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'turkish'		=>	array(
		'demoName'				=>	'Turkish',
		'liveURL'				=>	'http://www.highgradelab.com/sage/turkish/',
		'demoImg'				=>	'turkish.jpg',
		'xmlContentFile'		=>	'turkish.xml',
		'themeOptionsFile'		=>	'turkish.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'bistro'			=>	array(
		'demoName'				=>	'Bistro',
		'liveURL'				=>	'http://www.highgradelab.com/sage/bistro/',
		'demoImg'				=>	'bistro.jpg',
		'xmlContentFile'		=>	'bistro.xml',
		'themeOptionsFile'		=>	'bistro.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	array('bistro.zip'),
	),
	'burger'			=>	array(
		'demoName'				=>	'Burger',
		'liveURL'				=>	'http://www.highgradelab.com/sage/burger/',
		'demoImg'				=>	'buger-joint.jpg',
		'xmlContentFile'		=>	'burger.xml',
		'themeOptionsFile'		=>	'burger.json',
		'essentialGridFile'		=>	'burger.json',
		'revSliderZipFiles'		=>	false,
	),
	'cafe'			=>	array(
		'demoName'				=>	'Cafe',
		'liveURL'				=>	'http://www.highgradelab.com/sage/cafe/',
		'demoImg'				=>	'cafe.jpg',
		'xmlContentFile'		=>	'cafe.xml',
		'themeOptionsFile'		=>	'cafe.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'vegan'			=>	array(
		'demoName'				=>	'Vegan',
		'liveURL'				=>	'http://www.highgradelab.com/sage/vegan/',
		'demoImg'				=>	'raw-vegan.jpg',
		'xmlContentFile'		=>	'vegan.xml',
		'themeOptionsFile'		=>	'vegan.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'brewery'		=>	array(
		'demoName'				=>	'Brewery',
		'liveURL'				=>	'http://www.highgradelab.com/sage/brewery/',
		'demoImg'				=>	'brewery.jpg',
		'xmlContentFile'		=>	'brewery.xml',
		'themeOptionsFile'		=>	'brewery.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'tapas'			=>	array(
		'demoName'				=>	'Tapas',
		'liveURL'				=>	'http://www.highgradelab.com/sage/tapas-bar/',
		'demoImg'				=>	'tapas-bar.jpg',
		'xmlContentFile'		=>	'tapas.xml',
		'themeOptionsFile'		=>	'tapas.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	array('tapas.zip'),
	),
	'teahouse'		=>	array(
		'demoName'				=>	'Tea House',
		'liveURL'				=>	'http://www.highgradelab.com/sage/tea-house/',
		'demoImg'				=>	'tea-house.jpg',
		'xmlContentFile'		=>	'teahouse.xml',
		'themeOptionsFile'		=>	'teahouse.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'trattoria'		=>	array(
		'demoName'				=>	'Trattoria',
		'liveURL'				=>	'http://www.highgradelab.com/sage/trattoria/',
		'demoImg'				=>	'trattoria.jpg',
		'xmlContentFile'		=>	'trattoria.xml',
		'themeOptionsFile'		=>	'trattoria.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	array('trattoria.zip'),
	),
	'foodtruck'		=>	array(
		'demoName'				=>	'Food Truck',
		'liveURL'				=>	'http://www.highgradelab.com/sage/food-truck/',
		'demoImg'				=>	'food-truck.jpg',
		'xmlContentFile'		=>	'foodtruck.xml',
		'themeOptionsFile'		=>	'foodtruck.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'cocktail'		=>	array(
		'demoName'				=>	'Cocktail',
		'liveURL'				=>	'http://www.highgradelab.com/sage/cocktail-bar/',
		'demoImg'				=>	'cocktail-bar.jpg',
		'xmlContentFile'		=>	'cocktail.xml',
		'themeOptionsFile'		=>	'cocktail.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	array('cocktail.zip'),
	),
	'fusion'			=>	array(
		'demoName'				=>	'Fusion',
		'liveURL'				=>	'http://www.highgradelab.com/sage/fusion/',
		'demoImg'				=>	'fusion.jpg',
		'xmlContentFile'		=>	'fusion.xml',
		'themeOptionsFile'		=>	'fusion.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'cigarbar'		=>	array(
		'demoName'				=>	'Cigar Bar',
		'liveURL'				=>	'http://www.highgradelab.com/sage/cigar-bar/',
		'demoImg'				=>	'cigar-bar.jpg',
		'xmlContentFile'		=>	'cigarbar.xml',
		'themeOptionsFile'		=>	'cigarbar.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'chinese'		=>	array(
		'demoName'				=>	'Chinese',
		'liveURL'				=>	'http://www.highgradelab.com/sage/chinese/',
		'demoImg'				=>	'chinese.jpg',
		'xmlContentFile'		=>	'chinese.xml',
		'themeOptionsFile'		=>	'chinese.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	array('chinese.zip'),
	),
	'sushi'			=>	array(
		'demoName'				=>	'Sushi',
		'liveURL'				=>	'http://www.highgradelab.com/sage/sushi/',
		'demoImg'				=>	'sushi.jpg',
		'xmlContentFile'		=>	'sushi.xml',
		'themeOptionsFile'		=>	'sushi.json',
		'essentialGridFile'		=>	'sushi.json',
		'revSliderZipFiles'		=>	array('sushi.zip'),
	),
	'candyshop'		=>	array(
		'demoName'				=>	'Candy Shop',
		'liveURL'				=>	'http://www.highgradelab.com/sage/candy-shop/',
		'demoImg'				=>	'candy-shop.jpg',
		'xmlContentFile'		=>	'candyshop.xml',
		'themeOptionsFile'		=>	'candyshop.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'chocolaterie'	=>	array(
		'demoName'				=>	'Chocolaterie',
		'liveURL'				=>	'http://www.highgradelab.com/sage/chocolaterie/',
		'demoImg'				=>	'chocolaterie.jpg',
		'xmlContentFile'		=>	'chocolaterie.xml',
		'themeOptionsFile'		=>	'chocolaterie.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'gelato'			=>	array(
		'demoName'				=>	'Gelato',
		'liveURL'				=>	'http://www.highgradelab.com/sage/gelato/',
		'demoImg'				=>	'gelato.jpg',
		'xmlContentFile'		=>	'gelato.xml',
		'themeOptionsFile'		=>	'gelato.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'pizza'			=>	array(
		'demoName'				=>	'pizza',
		'liveURL'				=>	'http://www.highgradelab.com/sage/pizza/',
		'demoImg'				=>	'pizza.jpg',
		'xmlContentFile'		=>	'pizza.xml',
		'themeOptionsFile'		=>	'pizza.json',
		'essentialGridFile'		=>	'pizza.json',
		'revSliderZipFiles'		=>	array('pizza.zip'),
	),
	'fastfood'		=>	array(
		'demoName'				=>	'Fast Food',
		'liveURL'				=>	'http://www.highgradelab.com/sage/fast-food/',
		'demoImg'				=>	'fast-food.jpg',
		'xmlContentFile'		=>	'fastfood.xml',
		'themeOptionsFile'		=>	'fastfood.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'pub'			=>	array(
		'demoName'				=>	'Pub',
		'liveURL'				=>	'http://www.highgradelab.com/sage/pub/',
		'demoImg'				=>	'pub.jpg',
		'xmlContentFile'		=>	'pub.xml',
		'themeOptionsFile'		=>	'pub.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'takeaway'		=>	array(
		'demoName'				=>	'Take Away',
		'liveURL'				=>	'http://www.highgradelab.com/sage/take-away/',
		'demoImg'				=>	'take-away.jpg',
		'xmlContentFile'		=>	'takeaway.xml',
		'themeOptionsFile'		=>	'takeaway.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'greek'			=>	array(
		'demoName'				=>	'Greek',
		'liveURL'				=>	'http://www.highgradelab.com/sage/greek/',
		'demoImg'				=>	'greek.jpg',
		'xmlContentFile'		=>	'greek.xml',
		'themeOptionsFile'		=>	'greek.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'donuts'			=>	array(
		'demoName'				=>	'Donuts',
		'liveURL'				=>	'http://www.highgradelab.com/sage/donuts/',
		'demoImg'				=>	'donuts.jpg',
		'xmlContentFile'		=>	'donuts.xml',
		'themeOptionsFile'		=>	'donuts.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'irish'			=>	array(
		'demoName'				=>	'Irish',
		'liveURL'				=>	'http://www.highgradelab.com/sage/irish/',
		'demoImg'				=>	'irish-pub.jpg',
		'xmlContentFile'		=>	'irish.xml',
		'themeOptionsFile'		=>	'irish.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	array('irish.zip'),
	),
	'cakes'			=>	array(
		'demoName'				=>	'Cakes',
		'liveURL'				=>	'http://www.highgradelab.com/sage/cakes/',
		'demoImg'				=>	'cakes.jpg',
		'xmlContentFile'		=>	'cakes.xml',
		'themeOptionsFile'		=>	'cakes.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	array('cakes.zip'),
	),
	'indian'			=>	array(
		'demoName'				=>	'Indian',
		'liveURL'				=>	'http://www.highgradelab.com/sage/indian/',
		'demoImg'				=>	'indian.jpg',
		'xmlContentFile'		=>	'indian.xml',
		'themeOptionsFile'		=>	'indian.json',
		'essentialGridFile'		=>	'indian.json',
		'revSliderZipFiles'		=>	array('indian.zip'),
	),
	'foodblog'		=>	array(
		'demoName'				=>	'Food Blog',
		'liveURL'				=>	'http://www.highgradelab.com/sage/food-blog/',
		'demoImg'				=>	'food-blog.jpg',
		'xmlContentFile'		=>	'foodblog.xml',
		'themeOptionsFile'		=>	'foodblog.json',
		'essentialGridFile'		=>	'foodblog.json',
		'revSliderZipFiles'		=>	false,
	),
	'comingsoon'		=>	array(
		'demoName'				=>	'Coming Soon',
		'liveURL'				=>	'http://www.highgradelab.com/sage/coming-soon/',
		'demoImg'				=>	'coming-soon.jpg',
		'xmlContentFile'		=>	'comingsoon.xml',
		'themeOptionsFile'		=>	'comingsoon.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
)
?>